import type { BuildingId, BuildingSpec, BuildTabId, Resources } from './types';

/** Grilla planeta GO II: 10×8 = 80 módulos */
export const GRID_COLS = 10;
export const GRID_ROWS = 8;
export const TILE_W = 72;
export const TILE_H = 38;
export const MAX_QUEUE = 5;

export const STARTING_RESOURCES: Resources = {
  metal: 12_000,
  crystal: 10_000,
  energy: 10_000,
  nova: 8_000,
  credits: 12_000,
};

export const BUILD_TABS: { id: BuildTabId; label: string }[] = [
  { id: 'produccion', label: 'Recursos' },
  { id: 'infra', label: 'Desarrollo' },
  { id: 'civil', label: 'Civil' },
  { id: 'militar', label: 'Milicia' },
  { id: 'defensa', label: 'Defensa' },
];

export const BUILDING_SPECS: BuildingSpec[] = [
  {
    id: 'core_drill',
    name: 'Perforador de Núcleo',
    description: 'Extrae aleación bruta del manto orbital.',
    tab: 'produccion',
    footprint: { w: 1, h: 1 },
    cost: { metal: 80, crystal: 15, energy: 20, nova: 0, credits: 40 },
    buildSeconds: 6,
    maxOnBase: 99,
    accent: '#38bdf8',
    color: '#0c4a6e',
  },
  {
    id: 'crystal_lattice',
    name: 'Cristalizador de Vacío',
    description: 'Sintetiza cristales de fase para módulos avanzados.',
    tab: 'produccion',
    footprint: { w: 2, h: 1 },
    cost: { metal: 120, crystal: 40, energy: 30, nova: 10, credits: 60 },
    buildSeconds: 8,
    maxOnBase: 99,
    accent: '#a78bfa',
    color: '#4c1d95',
  },
  {
    id: 'flux_reactor',
    name: 'Reactor de Flujo',
    description: 'Genera energía estable para la base.',
    tab: 'produccion',
    footprint: { w: 2, h: 1 },
    cost: { metal: 150, crystal: 50, energy: 0, nova: 20, credits: 80 },
    buildSeconds: 9,
    maxOnBase: 99,
    accent: '#4ade80',
    color: '#14532d',
  },
  {
    id: 'nova_collider',
    name: 'Colisionador Nova',
    description: 'Concentra materia Nova para sistemas de élite.',
    tab: 'produccion',
    footprint: { w: 2, h: 2 },
    cost: { metal: 200, crystal: 120, energy: 80, nova: 0, credits: 150 },
    buildSeconds: 12,
    maxOnBase: 4,
    accent: '#f472b6',
    color: '#831843',
  },
  {
    id: 'vault_silo',
    name: 'Bóveda de Reservas',
    description: 'Amplía capacidad de almacenamiento.',
    tab: 'civil',
    footprint: { w: 2, h: 2 },
    cost: { metal: 180, crystal: 100, energy: 40, nova: 0, credits: 120 },
    buildSeconds: 10,
    maxOnBase: 99,
    accent: '#fbbf24',
    color: '#78350f',
  },
  {
    id: 'habitat_pod',
    name: 'Anillo Hab-A',
    description: 'Habitats para tripulación y operarios.',
    tab: 'civil',
    footprint: { w: 2, h: 2 },
    cost: { metal: 140, crystal: 30, energy: 50, nova: 0, credits: 90 },
    buildSeconds: 8,
    maxOnBase: 99,
    accent: '#86efac',
    color: '#166534',
  },
  {
    id: 'blueforge_citadel',
    name: 'Ciudadela Blueforge',
    description: 'Centro de mando 3D (Meshy GLB). Arrastra al terreno cuadrado.',
    tab: 'infra',
    footprint: { w: 3, h: 3 },
    cost: { metal: 400, crystal: 200, energy: 150, nova: 80, credits: 300 },
    buildSeconds: 12,
    maxOnBase: 1,
    accent: '#818cf8',
    color: '#312e81',
  },
  {
    id: 'nexus_spire',
    name: 'Espina del Nexo',
    description: 'Centro de mando de tu sector. Una por base.',
    tab: 'infra',
    footprint: { w: 3, h: 3 },
    cost: { metal: 500, crystal: 280, energy: 200, nova: 100, credits: 400 },
    buildSeconds: 25,
    maxOnBase: 1,
    accent: '#818cf8',
    color: '#312e81',
    unlock: { buildingId: 'flux_reactor', level: 1, label: 'Reactor de Flujo' },
  },
  {
    id: 'prism_lab',
    name: 'Laboratorio Prismático',
    description: 'Investigación y desbloqueo de módulos.',
    tab: 'infra',
    footprint: { w: 2, h: 2 },
    cost: { metal: 400, crystal: 350, energy: 150, nova: 80, credits: 500 },
    buildSeconds: 18,
    maxOnBase: 1,
    accent: '#c4b5fd',
    color: '#5b21b6',
    unlock: { buildingId: 'nexus_spire', level: 1, label: 'Espina del Nexo' },
  },
  {
    id: 'trade_nexus',
    name: 'Nexo de Trueque',
    description: 'Intercambio con mercaderes del sector.',
    tab: 'civil',
    footprint: { w: 2, h: 2 },
    cost: { metal: 300, crystal: 150, energy: 100, nova: 50, credits: 600 },
    buildSeconds: 14,
    maxOnBase: 1,
    accent: '#fcd34d',
    color: '#92400e',
    unlock: { buildingId: 'nexus_spire', level: 1, label: 'Espina del Nexo' },
  },
  {
    id: 'forge_dock',
    name: 'Doca de Forja',
    description: 'Fabricación y reparación de naves.',
    tab: 'militar',
    footprint: { w: 3, h: 2 },
    cost: { metal: 900, crystal: 400, energy: 300, nova: 200, credits: 700 },
    buildSeconds: 22,
    maxOnBase: 1,
    accent: '#60a5fa',
    color: '#1e3a8a',
    unlock: { buildingId: 'nexus_spire', level: 1, label: 'Espina del Nexo' },
  },
  {
    id: 'launch_ring',
    name: 'Anillo de Despliegue',
    description: 'Despliegue de flotas en órbita baja.',
    tab: 'militar',
    footprint: { w: 3, h: 2 },
    cost: { metal: 650, crystal: 320, energy: 250, nova: 150, credits: 550 },
    buildSeconds: 20,
    maxOnBase: 1,
    accent: '#7dd3fc',
    color: '#0c4a6e',
    unlock: { buildingId: 'forge_dock', level: 1, label: 'Doca de Forja' },
  },
  {
    id: 'pulse_turret',
    name: 'Cañón de Pulso',
    description: 'Defensa perimetral anti-incursión.',
    tab: 'defensa',
    footprint: { w: 1, h: 1 },
    cost: { metal: 350, crystal: 120, energy: 180, nova: 60, credits: 200 },
    buildSeconds: 14,
    maxOnBase: 99,
    accent: '#f87171',
    color: '#7f1d1d',
    unlock: { buildingId: 'prism_lab', level: 1, label: 'Laboratorio Prismático' },
  },
  {
    id: 'sweep_array',
    name: 'Matriz de Barrido',
    description: 'Detección de flotas hostiles.',
    tab: 'defensa',
    footprint: { w: 2, h: 1 },
    cost: { metal: 280, crystal: 90, energy: 120, nova: 40, credits: 180 },
    buildSeconds: 12,
    maxOnBase: 1,
    accent: '#94a3b8',
    color: '#334155',
    unlock: { buildingId: 'nexus_spire', level: 1, label: 'Espina del Nexo' },
  },
];

export function getSpec(id: BuildingId): BuildingSpec | undefined {
  return BUILDING_SPECS.find((b) => b.id === id);
}

export function specsForTab(tab: BuildTabId): BuildingSpec[] {
  return BUILDING_SPECS.filter((b) => b.tab === tab);
}
