-- ============================================================
-- SEED: 100 Comandantes de Galaxy Online 2
-- Generado automaticamente desde go2-commander-data.ts
-- ============================================================

INSERT INTO commander_cards (name, rarity, base_accuracy, base_speed, base_dodge, base_electron, expertise, skill_name, skill_description) VALUES
  ('Alicia', 'common', 9, 3, 7, 5, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "C"}'::jsonb, 'Inspiration', 'Has a chance to increase the damage dealt by the ship in the next slot of the formation by 30%.'),
  ('Angla', 'common', 4, 4, 5, 7, '{"ballistic": "B", "directional": "C", "missile": "B", "ship_based": "A"}'::jsonb, 'Fleet EMT', 'Reduces hospital time and prevents anyone from killing the Commander.'),
  ('Donna', 'common', 7, 4, 4, 8, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'Defensive Intensity', 'Has a chance to restore 15% of maximum Shields at the start of each round.'),
  ('Essido', 'common', 8, 5, 6, 8, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "S"}'::jsonb, 'Ship-based Expertise', 'Increases the damage of Ship-based Weapons.'),
  ('Heloyce', 'common', 7, 2, 8, 4, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "C"}'::jsonb, 'Stability', 'Removes the formation penalty when a fleet is under attack and increases fleet stability.'),
  ('Jason', 'common', 4, 2, 5, 5, '{"ballistic": "B", "directional": "C", "missile": "B", "ship_based": "C"}'::jsonb, 'Save Energy', 'Has a chance to prevent modules from consuming He3 while attacking or defending.'),
  ('Jerome', 'common', 5, 8, 2, 5, '{"ballistic": "B", "directional": "C", "missile": "B", "ship_based": "C"}'::jsonb, 'Curse', 'If attacked, the enemy will receive 10% more damage the next round (stackable).'),
  ('Kelly', 'common', 3, 9, 6, 5, '{"ballistic": "B", "directional": "C", "missile": "B", "ship_based": "C"}'::jsonb, 'Resourceful', 'Restores 15% of maximum Structures per round.'),
  ('Lawrence', 'common', 9, 4, 6, 8, '{"ballistic": "S", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'Ballistic Expertise', 'Increases the damage of ballistic weapons.'),
  ('Mantie', 'common', 14, 14, 14, 14, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'Command Strike', ''),
  ('Maxius', 'common', 10, 0, 5, 5, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "C"}'::jsonb, 'Allied Strike', 'Has a chance to increase the accuracy of all friendly forces within 4 spaces by 5.'),
  ('Motima', 'common', 8, 2, 6, 6, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "C"}'::jsonb, 'Accuracy', 'Has a chance to use the highest possible hit chance when attacking the enemy.'),
  ('Natiya', 'common', 8, 8, 6, 8, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'First Strike', ''),
  ('Panis', 'common', 5, 5, 6, 12, '{"ballistic": "B", "directional": "C", "missile": "B", "ship_based": "A"}'::jsonb, 'Intercept', 'Increases the chance of air interception.'),
  ('Rayllf', 'common', 6, 8, 7, 7, '{"ballistic": "B", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'Armor Repair', 'Has a chance to increase ship defense by 5 per round. This effect lasts for 1 round.'),
  ('Reggie', 'common', 5, 3, 8, 4, '{"ballistic": "B", "directional": "C", "missile": "B", "ship_based": "C"}'::jsonb, 'Paralyze', ''),
  ('Shaba', 'common', 8, 10, 5, 5, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "C"}'::jsonb, 'Allied Evasion', 'Increases the dodge chance of friendly forces within 4 spaces by 5 (stackable).'),
  ('Sofia', 'common', 7, 5, 11, 6, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "C"}'::jsonb, 'Maneuvering', 'Has a chance to move an extra 3 spaces.'),
  ('Taude', 'common', 7, 7, 4, 4, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "C"}'::jsonb, 'Lucky Shot', 'Has a chance to deal Lucky Shot, which increases the chance of shooting down a target by 50%.'),
  ('Tyren', 'common', 10, 5, 7, 5, '{"ballistic": "A", "directional": "A", "missile": "S", "ship_based": "C"}'::jsonb, 'Missile Expertise', 'Increases the damage of missiles.'),
  ('Vinna', 'common', 6, 6, 6, 6, '{"ballistic": "B", "directional": "A", "missile": "B", "ship_based": "C"}'::jsonb, 'Cunning', 'Reduces level-up requirements by 30%. Also has a chance to increase one stat by 10 when an attack connects. This effect lasts until the end of combat.'),
  ('Wayne', 'common', 8, 4, 9, 2, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "C"}'::jsonb, 'Lucky Hit', 'Has a chance to deal double damage to the enemy.'),
  ('Andrew', 'super', 5, 10, 6, 1, '{"ballistic": "B", "directional": "C", "missile": "B", "ship_based": "C"}'::jsonb, 'Acrobatics', ''),
  ('Anna', 'super', 9, 8, 10, 5, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "C"}'::jsonb, 'Pierce', 'Attacks have a chance to deal an extra 40% Piercing damage.'),
  ('Annata', 'super', 10, 8, 5, 8, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'Allied Support', 'Increases the Shields and Structures of friendly forces within 4 steps by 8% after each round.'),
  ('Bruce', 'super', 6, 8, 8, 12, '{"ballistic": "B", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'Drain Supplies', ''),
  ('Eveline', 'super', 7, 6, 9, 5, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "C"}'::jsonb, 'Find Weakness', ''),
  ('Evi', 'super', 8, 5, 9, 5, '{"ballistic": "A", "directional": "S", "missile": "B", "ship_based": "C"}'::jsonb, 'Directional Expertise', 'Increases the damage of Directional Weapons.'),
  ('Gastaf', 'super', 12, 0, 10, 7, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'Deadly Strike', 'Has an increased chance to deal critical strikes.'),
  ('Jakar', 'super', 9, 3, 5, 4, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "C"}'::jsonb, 'Aegis Shatter', ''),
  ('Joseph', 'super', 4, 10, 7, 17, '{"ballistic": "B", "directional": "C", "missile": "B", "ship_based": "A"}'::jsonb, 'Vengeance', ''),
  ('Leo', 'super', 5, 9, 6, 8, '{"ballistic": "B", "directional": "C", "missile": "B", "ship_based": "A"}'::jsonb, 'Intimidate', 'Has a chance to reduce the Durability, Structures and Shields of enemies within 2 steps by 5% after every turn.'),
  ('Linda', 'super', 10, 9, 7, 7, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'Broadside', 'Attacks have a chance to deal an extra 50% Scattering damage.'),
  ('Lynn', 'super', 8, 5, 6, 3, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "C"}'::jsonb, 'Victory Rush', ''),
  ('Nick', 'super', 5, 4, 5, 2, '{"ballistic": "B", "directional": "C", "missile": "B", "ship_based": "C"}'::jsonb, 'Divine Intervention', 'Has a chance to avoid damage.'),
  ('Penni', 'super', 10, 10, 10, 10, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'Last Stand', 'Has a chance to deal triple damage when attacking, but also inflicts 10% damage to the ship.'),
  ('Raslin', 'super', 8, 7, 9, 10, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'Fear', ''),
  ('Ringel', 'super', 9, 5, 9, 3, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "C"}'::jsonb, 'Ignite', 'Has a chance to inflict an additional 30% of the damage last dealt to the enemy when the next round begins.'),
  ('Rocky', 'super', 12, 4, 8, 5, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "C"}'::jsonb, 'Brutal Strength', ''),
  ('Sylva', 'super', 7, 5, 5, 2, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "C"}'::jsonb, 'Smash', 'Has a chance to deal up to 2.5 times the damage to a fortress.'),
  ('Sylla', 'super', 5, 9, 5, 5, '{"ballistic": "B", "directional": "C", "missile": "B", "ship_based": "C"}'::jsonb, 'Fleet Link', 'Has a chance to reduce damage taken by 15% and enables all ships to share damage.'),
  ('Todd', 'super', 30, 8, 5, 6, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "C"}'::jsonb, 'Consecutive Strike', 'While attacking, there is a chance of attacking the target twice.'),
  ('Aileen', 'legendary', 8, 8, 8, 8, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'Command Break', ''),
  ('Bain', 'legendary', 14, 12, 18, 16, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'Reckoning', ''),
  ('Bart', 'legendary', 5, 3, 5, 3, '{"ballistic": "B", "directional": "C", "missile": "B", "ship_based": "C"}'::jsonb, 'Raid', 'Has a chance to dodge attacks and increase Attack Power by 15% for one round.'),
  ('Callisto', 'legendary', 14, 20, 15, 20, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'A Fire Rises', 'While attacking, has a chance to increase attack strength by 10%. Can be stacked and remains in effect until end of the battle.'),
  ('Carlos', 'legendary', 15, 5, 10, 10, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'Fear Fiend', 'Deals additional damage to enemy fleet ship structures. Actual amounts are based on the amount of damage dealt to enemy ship shields.'),
  ('Cassius', 'legendary', 15, 15, 15, 15, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'Knockout Blow', 'When attacking, Cassius has a chance to move the enemy fleet back 3 spaces. Can only be used once per turn.'),
  ('Circe', 'legendary', 15, 10, 12, 22, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'Hex', 'While defending against an attack, has a chance to prevent the enemy commander from using skills in the next Round.'),
  ('Dilira', 'legendary', 10, 15, 10, 12, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'Renewal', 'Has a chance to fully restore Shields and Durability.'),
  ('Hellen', 'legendary', 11, 5, 7, 16, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'Rapid Reload', 'When attacking, there is a chance to instantly finish reloading weapons.'),
  ('Krina Klaus', 'legendary', 20, 20, 20, 20, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, '', ''),
  ('Maletiz', 'legendary', 2, 2, 2, 2, '{"ballistic": "B", "directional": "C", "missile": "B", "ship_based": "C"}'::jsonb, 'Revenge', 'Has a chance to absorb all damage and reflect it back to the attacker.'),
  ('Marcus', 'legendary', 8, 6, 8, 3, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "C"}'::jsonb, 'Breakthrough', ''),
  ('Medusa', 'legendary', 20, 14, 18, 12, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'Gorgon Gaze', 'Has a chance to cause the enemy fleet to skip its next Round when Medusa is attacked.'),
  ('Miller', 'legendary', 0, 0, 0, 0, '{"ballistic": "B", "directional": "C", "missile": "B", "ship_based": "C"}'::jsonb, 'Pulverizer', ''),
  ('Nora', 'legendary', 9, 4, 8, 3, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "C"}'::jsonb, 'Massacre', 'Has a chance to destroy enemy troops when they attack. This effect can only be initiated once per round.'),
  ('Rafia', 'legendary', 3, 3, 5, 2, '{"ballistic": "B", "directional": "C", "missile": "B", "ship_based": "C"}'::jsonb, 'Stability Control', ''),
  ('Rayo', 'legendary', 13, 13, 13, 13, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'Superior Command', ''),
  ('Robert', 'legendary', 20, 4, 10, 5, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "C"}'::jsonb, 'Massacre', ''),
  ('Sandora', 'legendary', 9, 7, 8, 7, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'Lucky Strike', 'Has a chance to deal 30% Scattering damage to all enemy forces.'),
  ('Singhri', 'legendary', 12, 12, 12, 12, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'Copycat', ''),
  ('Stani', 'legendary', 5, 8, 5, 10, '{"ballistic": "B", "directional": "C", "missile": "B", "ship_based": "A"}'::jsonb, 'Interference', 'Has a chance to prevent the enemy from moving and attacking for the next round.'),
  ('Titan', 'legendary', 35, 35, 35, 35, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'Adaptive Mutualism', ''),
  ('Venus', 'legendary', 15, 23, 24, 12, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'Gift of Romance', 'Increases damage negation of all shield modules in the fleet.'),
  ('Carbuncle Cohort', 'divine', 9, 22, 11, 15, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'Corrosive Coil', 'Will reflect 20% of the original damage taken, and then further reduce damage taken by 15%, and finally spread the remaining damage equally across all ships in the fleet.'),
  ('Deadly Duo', 'divine', 19, 17, 17, 12, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'Crucifer Sweep', 'This skill has a chance to deal an additional 50% Scattering Damage and 40% Piercing damage during all attacks.'),
  ('Death from Above', 'divine', 24, 24, 24, 24, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, '', ''),
  ('Desolate Prayers', 'divine', 20, 20, 13, 18, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'Decaying Wane', 'This skill has the chance to lower all 4 stats of an enemy commander to 0. The target will also be immobilized in the next round.'),
  ('Dopplegangers', 'divine', 34, 45, 44, 45, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'Fierce Mutation', ''),
  ('Enduring Chorus', 'divine', 8, 19, 21, 6, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "C"}'::jsonb, 'Renewed Faith', 'Has a chance each round to fully restore all Shield and Structure points and increase the Dodge attribute of all friendly forces within 4 spaces by 5. This buff can be stacked.'),
  ('Ererbus Errants', 'divine', 31, 22, 11, 34, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'Shadow Storm', 'Each time Erebus Errants levels up, the total value of their 4 attributes will increase by an additional 5 points. Also has a chance to negate all damage when attacked.'),
  ('Eschaton Adventists', 'divine', 38, 30, 31, 25, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'Abject Humiliation', ''),
  ('Eternal Terrors', 'divine', 29, 10, 11, 23, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'Battle Preparations', ''),
  ('Fairy & Fiend', 'divine', 22, 10, 20, 10, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'Double Whammy', ''),
  ('Fatal Furies', 'divine', 30, 15, 14, 12, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'Battering Barrage', ''),
  ('Fearmongers', 'divine', 19, 15, 12, 21, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'Omen of Doom', 'While attacking or defending, has a chance to increase enemy He3 cost by 5 times and reduce enemy attack power by 50% until end of next round.'),
  ('Feral Raptors', 'divine', 18, 14, 20, 10, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'Suicide Strike', 'Chance to deal 6x damage while attacking but also reflects 10% of damage back to your ships.'),
  ('Frontline Surge', 'divine', 15, 10, 17, 3, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "C"}'::jsonb, 'Pioneer Prowl', 'This skill has a chance to move fleets an additional 3 spaces and increase attack values by 10% for every space that fleet moves.'),
  ('Hand of Lelantos', 'divine', 36, 34, 32, 34, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'Unseen Strike', ''),
  ('Hekatian Witnesses', 'divine', 36, 37, 35, 34, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'Hekatian Edict', 'Each time level up, the total increment of four attributes is increased by an additional 5 points. Have a chance to destroy an entire ship stack each time it is dealt damage.'),
  ('Homeric Hellions', 'divine', 38, 45, 25, 12, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'TBD', 'Each time level up, the total increment of four attributes is increased by an additional 5 points.'),
  ('Impending Doom', 'divine', 10, 12, 7, 17, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'Insidious Infliction', 'This skill increases the dodge rate of your ships and, if attacked, will deal 10% more damage the next round (stackable).'),
  ('Indomitable Duo', 'divine', 12, 25, 17, 14, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'Divine Barrier', ''),
  ('Iron Maidens', 'divine', 10, 21, 19, 5, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "C"}'::jsonb, 'Fountain of Youth', ''),
  ('Kismet Beams', 'divine', 25, 20, 10, 5, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "C"}'::jsonb, 'Supreme Smite', 'This skill has a chance to deal 2x damage to the enemy and 30% Scattering damage to all enemy fleets.'),
  ('Leech Lurkers', 'divine', 17, 12, 32, 13, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'Covert Syphon', 'Reduces the chance of being hit and increases Attack Power by 15% for one round. Additional chance to reduce the Durability, Structures and Shields of enemies within 2 steps by 5% each turn.'),
  ('Light & Darkness', 'divine', 12, 15, 21, 3, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "C"}'::jsonb, 'Darkened Halo', 'This skill increases the Shield and Structure values of friendly fleets within 4 steps by 8% after each round and has a chance to reduce enemy Durability, structures, and Shields within 2 steps by 5% '),
  ('Lurking Light', 'divine', 11, 7, 24, 12, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'Phasing Halo', 'Has a chance to dodge attacks, increase Attack Power by 15% for one round, and increase Shield and Structure values of friendly forces within 4 spaces by 8% at end of the round.'),
  ('Pernicious Princes', 'divine', 20, 20, 20, 20, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'Chain Vortex', ''),
  ('Rays of Destiny', 'divine', 21, 12, 15, 9, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'Judgement', 'This skill has a chance to deal an additional 30% Scattering damage to all enemy forces and reflect all absorbed damage to its source.'),
  ('Rex Scuta', 'divine', 18, 21, 15, 18, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'Immunity', ''),
  ('The Ravagers', 'divine', 14, 10, 13, 11, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'Smash and Grab', 'If all ships in a single enemy fleet slot are destroyed by ships in a single fleet slot, Attack Power of those ships will double. This buff can be stacked up to 8 times. There is also a chance that th'),
  ('Suicidal Sirens', 'divine', 31, 3, 12, 20, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'Risky Surge', 'Chance to deal 3x damage and instantly reload weapons, but also reflects 10% damage to attacking ship.'),
  ('Summa Cum Laude', 'divine', 24, 9, 23, 12, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'Verdant Force', ''),
  ('Tactical Wizards', 'divine', 9, 16, 12, 22, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'Bamboozle', 'Chance to avoid damage and increase enemy He3 costs by up to 5 times.'),
  ('The Twin Torpedoes', 'divine', 30, 0, 10, 7, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'Sharpshooter Storm', 'This skill increases the critical strike rate of the commanded fleet and the chance of attacking the target twice.'),
  ('Victory Roar', 'divine', 17, 16, 19, 15, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'Eradicate', ''),
  ('Wildfire', 'divine', 35, 5, 9, 18, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'Trigger Happy', 'Chance to deal 30% Scattering damage to enemy ships and instantly reload weapons.'),
  ('Winter Knights', 'divine', 15, 34, 30, 20, '{"ballistic": "A", "directional": "A", "missile": "B", "ship_based": "A"}'::jsonb, 'TBD', 'Each time level up, the total increment of four attributes is increased by an additional 5 points.');

ON CONFLICT (name) DO NOTHING;
