export type Rarity = 'common' | 'super' | 'legendary' | 'divine';

export interface EquipmentItem {
  id: string;
  name: string;
  quality: 'S' | 'A' | 'B' | 'C' | 'D';
  icon: string;
}

export interface CommanderStats {
  accuracy: number;
  speed: number;
  dodge: number;
  electron: number;
}

export interface Commander {
  id: string;
  name: string;
  rarity: Rarity;
  level: number;
  exp: number;
  expMax: number;
  stars: number;
  skill: string;
  status: string;
  stats: CommanderStats;
  equipment: {
    weapons: (EquipmentItem | null)[];
    defense: (EquipmentItem | null)[];
  };
}

// ============================================================
// RARITY VISUAL CONSTANTS
// ============================================================
export const RARITY_COLORS: Record<Rarity, string> = {
  common: '#4caf50',
  super: '#2196f3',
  legendary: '#9c27b0',
  divine: '#ff9800',
};

export const RARITY_DOT_CLASS: Record<Rarity, string> = {
  common: 'bg-[#4caf50]',
  super: 'bg-[#2196f3]',
  legendary: 'bg-[#9c27b0]',
  divine: 'bg-[#ff9800]',
};

export const QUALITY_COLORS: Record<string, { border: string; bg: string }> = {
  S: { border: 'border-[#ffd54f]', bg: 'bg-gradient-to-br from-[#b8860b] to-[#8b6914]' },
  A: { border: 'border-[#4caf50]', bg: 'bg-gradient-to-br from-[#2e7d32] to-[#1b5e20]' },
  B: { border: 'border-[#42a5f5]', bg: 'bg-gradient-to-br from-[#1565c0] to-[#0d47a1]' },
  C: { border: 'border-[#757575]', bg: 'bg-gradient-to-br from-[#616161] to-[#424242]' },
  D: { border: 'border-[#e53935]', bg: 'bg-gradient-to-br from-[#c62828] to-[#8e0000]' },
};

// ============================================================
// EXP MAX BY RARITY
// ============================================================
export const EXP_MAX_BY_RARITY: Record<Rarity, number> = {
  common: 180,
  super: 200,
  legendary: 250,
  divine: 300,
};

// ============================================================
// MERGE PROBABILITY CONSTANTS
// ============================================================
export const MERGE_PROBABILITIES = {
  sameRarity: {
    common: 0.80,    // Skill -> Skill: 80%
    super: 0.60,     // Super -> Super: 60%
    legendary: 0.40, // Legendary -> Legendary: 40%
    divine: 0.25,    // Divine -> Divine: 25%
  },
  crossRarity: 0.10, // Cross-rarity merge: 10%
} as const;

// ============================================================
// SKILL RARITY (Common) — Corsairs' Gold 150
// ============================================================
// Alicia, Angla, Donna, Essido, Heloyce, Jason, Jerome, Kelly,
// Lawrence, Mantie, Maxius, Motima, Natiya, Panis, Rayllf, Reggie,
// Shaba, Sofia, Taude, Tyren, Vinna, Wayne

// ============================================================
// SUPER RARITY — Corsairs' Gold 300
// ============================================================
// Andrew, Anna, Annata, Bruce, Eveline, Evi, Gastaf, Jakar,
// Joseph, Leo, Linda, Lynn, Nick, Penni, Raslin, Ringel,
// Rocky, Sylva, Sylla, Todd

// ============================================================
// LEGENDARY RARITY — Corsairs' Gold 600
// ============================================================
// Aileen, Bain, Bart, Callisto, Carlos, Cassius, Circe, Dilira,
// Hellen, Krina Klaus, Maletiz, Marcus, Medusa, Miller, Nora,
// Rafia, Rayo, Robert, Sandora, Singhri, Stani, Titan, Venus

// ============================================================
// DIVINE RARITY — Corsairs' Gold 600
// ============================================================
// Carbuncle Cohort, Deadly Duo, Death from Above, Desolate Prayers,
// Dopplegangers, Enduring Chorus, Ererbus Errants, Eschaton Adventists,
// Eternal Terrors, Fairy & Fiend, Fatal Furies, Fearmongers,
// Feral Raptors, Frontline Surge, Hand of Lelantos, Hekatian Witnesses,
// Homeric Hellions, Impending Doom, Indomitable Duo, Iron Maidens,
// Kismet Beams, Leech Lurkers, Light & Darkness, Lurking Light,
// Pernicious Princes, Rays of Destiny, Rex Scuta, The Ravagers,
// Suicidal Sirens, Summa Cum Laude, Tactical Wizards, The Twin Torpedoes,
// Victory Roar, Wildfire, Winter Knights

// ============================================================
// EMPTY EQUIPMENT TEMPLATE
// ============================================================
const EMPTY_EQUIPMENT = {
  weapons: [null, null, null, null] as (EquipmentItem | null)[],
  defense: [null, null, null, null] as (EquipmentItem | null)[],
};

// ============================================================
// COMPLETE COMMANDER DATABASE (101 commanders)
// ============================================================
export const COMMANDERS: Commander[] = [
  // ----------------------------------------------------------
  // SKILL (Common) — 22 commanders
  // ----------------------------------------------------------
  {
    id: 'alicia',
    name: 'Alicia',
    rarity: 'common',
    level: 1,
    exp: 0,
    expMax: 180,
    stars: 1,
    skill: 'Inspiration',
    status: 'Normal',
    stats: { accuracy: 9, speed: 3, dodge: 7, electron: 5 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'angla',
    name: 'Angla',
    rarity: 'common',
    level: 1,
    exp: 0,
    expMax: 180,
    stars: 1,
    skill: 'Fleet EMT',
    status: 'Normal',
    stats: { accuracy: 4, speed: 4, dodge: 5, electron: 7 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'donna',
    name: 'Donna',
    rarity: 'common',
    level: 1,
    exp: 0,
    expMax: 180,
    stars: 1,
    skill: 'Defensive Intensity',
    status: 'Normal',
    stats: { accuracy: 7, speed: 4, dodge: 4, electron: 8 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'essido',
    name: 'Essido',
    rarity: 'common',
    level: 1,
    exp: 0,
    expMax: 180,
    stars: 1,
    skill: 'Ship-based Expertise',
    status: 'Normal',
    stats: { accuracy: 8, speed: 5, dodge: 6, electron: 8 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'heloyc',
    name: 'Heloyce',
    rarity: 'common',
    level: 1,
    exp: 0,
    expMax: 180,
    stars: 1,
    skill: 'Stability',
    status: 'Normal',
    stats: { accuracy: 7, speed: 2, dodge: 8, electron: 4 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'jason',
    name: 'Jason',
    rarity: 'common',
    level: 1,
    exp: 0,
    expMax: 180,
    stars: 1,
    skill: 'Save Energy',
    status: 'Normal',
    stats: { accuracy: 4, speed: 2, dodge: 5, electron: 5 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'jerome',
    name: 'Jerome',
    rarity: 'common',
    level: 1,
    exp: 0,
    expMax: 180,
    stars: 1,
    skill: 'Curse',
    status: 'Normal',
    stats: { accuracy: 5, speed: 8, dodge: 2, electron: 5 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'kelly',
    name: 'Kelly',
    rarity: 'common',
    level: 1,
    exp: 0,
    expMax: 180,
    stars: 1,
    skill: 'Resourceful',
    status: 'Normal',
    stats: { accuracy: 3, speed: 9, dodge: 6, electron: 5 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'lawrence',
    name: 'Lawrence',
    rarity: 'common',
    level: 1,
    exp: 0,
    expMax: 180,
    stars: 1,
    skill: 'Ballistic Expertise',
    status: 'Normal',
    stats: { accuracy: 9, speed: 4, dodge: 6, electron: 8 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'mantie',
    name: 'Mantie',
    rarity: 'common',
    level: 1,
    exp: 0,
    expMax: 180,
    stars: 1,
    skill: 'Command Strike',
    status: 'Normal',
    stats: { accuracy: 14, speed: 14, dodge: 14, electron: 14 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'maxius',
    name: 'Maxius',
    rarity: 'common',
    level: 1,
    exp: 0,
    expMax: 180,
    stars: 1,
    skill: 'Allied Strike',
    status: 'Normal',
    stats: { accuracy: 10, speed: 0, dodge: 5, electron: 5 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'motima',
    name: 'Motima',
    rarity: 'common',
    level: 1,
    exp: 0,
    expMax: 180,
    stars: 1,
    skill: 'Accuracy',
    status: 'Normal',
    stats: { accuracy: 8, speed: 2, dodge: 6, electron: 6 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'natiya',
    name: 'Natiya',
    rarity: 'common',
    level: 1,
    exp: 0,
    expMax: 180,
    stars: 1,
    skill: 'First Strike',
    status: 'Normal',
    stats: { accuracy: 8, speed: 8, dodge: 6, electron: 8 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'panis',
    name: 'Panis',
    rarity: 'common',
    level: 1,
    exp: 0,
    expMax: 180,
    stars: 1,
    skill: 'Intercept',
    status: 'Normal',
    stats: { accuracy: 5, speed: 5, dodge: 6, electron: 12 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'rayllf',
    name: 'Rayllf',
    rarity: 'common',
    level: 1,
    exp: 0,
    expMax: 180,
    stars: 1,
    skill: 'Armor Repair',
    status: 'Normal',
    stats: { accuracy: 6, speed: 8, dodge: 7, electron: 7 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'reggie',
    name: 'Reggie',
    rarity: 'common',
    level: 1,
    exp: 0,
    expMax: 180,
    stars: 1,
    skill: 'Paralyze',
    status: 'Normal',
    stats: { accuracy: 5, speed: 3, dodge: 8, electron: 4 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'shaba',
    name: 'Shaba',
    rarity: 'common',
    level: 1,
    exp: 0,
    expMax: 180,
    stars: 1,
    skill: 'Allied Evasion',
    status: 'Normal',
    stats: { accuracy: 8, speed: 10, dodge: 5, electron: 5 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'sofia',
    name: 'Sofia',
    rarity: 'common',
    level: 1,
    exp: 0,
    expMax: 180,
    stars: 1,
    skill: 'Maneuvering',
    status: 'Normal',
    stats: { accuracy: 7, speed: 5, dodge: 11, electron: 6 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'taude',
    name: 'Taude',
    rarity: 'common',
    level: 1,
    exp: 0,
    expMax: 180,
    stars: 1,
    skill: 'Lucky Shot',
    status: 'Normal',
    stats: { accuracy: 7, speed: 7, dodge: 4, electron: 4 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'tyren',
    name: 'Tyren',
    rarity: 'common',
    level: 1,
    exp: 0,
    expMax: 180,
    stars: 1,
    skill: 'Missile Expertise',
    status: 'Normal',
    stats: { accuracy: 10, speed: 5, dodge: 7, electron: 5 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'vinna',
    name: 'Vinna',
    rarity: 'common',
    level: 1,
    exp: 0,
    expMax: 180,
    stars: 1,
    skill: 'Cunning',
    status: 'Normal',
    stats: { accuracy: 6, speed: 6, dodge: 6, electron: 6 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'wayne',
    name: 'Wayne',
    rarity: 'common',
    level: 1,
    exp: 0,
    expMax: 180,
    stars: 1,
    skill: 'Lucky Hit',
    status: 'Normal',
    stats: { accuracy: 8, speed: 4, dodge: 9, electron: 2 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },

  // ----------------------------------------------------------
  // SUPER — 20 commanders
  // ----------------------------------------------------------
  {
    id: 'andrew',
    name: 'Andrew',
    rarity: 'super',
    level: 1,
    exp: 0,
    expMax: 200,
    stars: 1,
    skill: 'Acrobatics',
    status: 'Normal',
    stats: { accuracy: 5, speed: 10, dodge: 6, electron: 1 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'anna',
    name: 'Anna',
    rarity: 'super',
    level: 1,
    exp: 0,
    expMax: 200,
    stars: 1,
    skill: 'Pierce',
    status: 'Normal',
    stats: { accuracy: 9, speed: 8, dodge: 10, electron: 5 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'annata',
    name: 'Annata',
    rarity: 'super',
    level: 1,
    exp: 0,
    expMax: 200,
    stars: 1,
    skill: 'Allied Support',
    status: 'Normal',
    stats: { accuracy: 10, speed: 8, dodge: 5, electron: 8 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'bruce',
    name: 'Bruce',
    rarity: 'super',
    level: 1,
    exp: 0,
    expMax: 200,
    stars: 1,
    skill: 'Drain Supplies',
    status: 'Normal',
    stats: { accuracy: 6, speed: 8, dodge: 8, electron: 12 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'eveline',
    name: 'Eveline',
    rarity: 'super',
    level: 1,
    exp: 0,
    expMax: 200,
    stars: 1,
    skill: 'Find Weakness',
    status: 'Normal',
    stats: { accuracy: 7, speed: 6, dodge: 9, electron: 5 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'evi',
    name: 'Evi',
    rarity: 'super',
    level: 1,
    exp: 0,
    expMax: 200,
    stars: 1,
    skill: 'Directional Expertise',
    status: 'Normal',
    stats: { accuracy: 8, speed: 5, dodge: 9, electron: 5 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'gastaf',
    name: 'Gastaf',
    rarity: 'super',
    level: 1,
    exp: 0,
    expMax: 200,
    stars: 1,
    skill: 'Deadly Strike',
    status: 'Normal',
    stats: { accuracy: 12, speed: 0, dodge: 10, electron: 7 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'jakar',
    name: 'Jakar',
    rarity: 'super',
    level: 1,
    exp: 0,
    expMax: 200,
    stars: 1,
    skill: 'Aegis Shatter',
    status: 'Normal',
    stats: { accuracy: 9, speed: 3, dodge: 5, electron: 4 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'joseph',
    name: 'Joseph',
    rarity: 'super',
    level: 1,
    exp: 0,
    expMax: 200,
    stars: 1,
    skill: 'Vengeance',
    status: 'Normal',
    stats: { accuracy: 4, speed: 10, dodge: 7, electron: 17 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'leo',
    name: 'Leo',
    rarity: 'super',
    level: 1,
    exp: 0,
    expMax: 200,
    stars: 1,
    skill: 'Intimidate',
    status: 'Normal',
    stats: { accuracy: 5, speed: 9, dodge: 6, electron: 8 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'linda',
    name: 'Linda',
    rarity: 'super',
    level: 1,
    exp: 0,
    expMax: 200,
    stars: 1,
    skill: 'Broadside',
    status: 'Normal',
    stats: { accuracy: 10, speed: 9, dodge: 7, electron: 7 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'lynn',
    name: 'Lynn',
    rarity: 'super',
    level: 1,
    exp: 0,
    expMax: 200,
    stars: 1,
    skill: 'Victory Rush',
    status: 'Normal',
    stats: { accuracy: 8, speed: 5, dodge: 6, electron: 3 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'nick',
    name: 'Nick',
    rarity: 'super',
    level: 1,
    exp: 0,
    expMax: 200,
    stars: 1,
    skill: 'Divine Intervention',
    status: 'Normal',
    stats: { accuracy: 5, speed: 4, dodge: 5, electron: 2 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'penni',
    name: 'Penni',
    rarity: 'super',
    level: 1,
    exp: 0,
    expMax: 200,
    stars: 1,
    skill: 'Last Stand',
    status: 'Normal',
    stats: { accuracy: 10, speed: 10, dodge: 10, electron: 10 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'raslin',
    name: 'Raslin',
    rarity: 'super',
    level: 1,
    exp: 0,
    expMax: 200,
    stars: 1,
    skill: 'Fear',
    status: 'Normal',
    stats: { accuracy: 8, speed: 7, dodge: 9, electron: 10 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'ringel',
    name: 'Ringel',
    rarity: 'super',
    level: 1,
    exp: 0,
    expMax: 200,
    stars: 1,
    skill: 'Ignite',
    status: 'Normal',
    stats: { accuracy: 9, speed: 5, dodge: 9, electron: 3 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'rocky',
    name: 'Rocky',
    rarity: 'super',
    level: 1,
    exp: 0,
    expMax: 200,
    stars: 1,
    skill: 'Brutal Strength',
    status: 'Normal',
    stats: { accuracy: 12, speed: 4, dodge: 8, electron: 5 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'sylva',
    name: 'Sylva',
    rarity: 'super',
    level: 1,
    exp: 0,
    expMax: 200,
    stars: 1,
    skill: 'Smash',
    status: 'Normal',
    stats: { accuracy: 7, speed: 5, dodge: 5, electron: 2 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'sylla',
    name: 'Sylla',
    rarity: 'super',
    level: 1,
    exp: 0,
    expMax: 200,
    stars: 1,
    skill: 'Fleet Link',
    status: 'Normal',
    stats: { accuracy: 5, speed: 9, dodge: 5, electron: 5 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'todd',
    name: 'Todd',
    rarity: 'super',
    level: 1,
    exp: 0,
    expMax: 200,
    stars: 1,
    skill: 'Consecutive Strike',
    status: 'Normal',
    stats: { accuracy: 30, speed: 8, dodge: 5, electron: 6 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },

  // ----------------------------------------------------------
  // LEGENDARY — 24 commanders
  // ----------------------------------------------------------
  {
    id: 'aileen',
    name: 'Aileen',
    rarity: 'legendary',
    level: 1,
    exp: 0,
    expMax: 250,
    stars: 1,
    skill: 'Command Break',
    status: 'Normal',
    stats: { accuracy: 8, speed: 8, dodge: 8, electron: 8 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'bain',
    name: 'Bain',
    rarity: 'legendary',
    level: 1,
    exp: 0,
    expMax: 250,
    stars: 1,
    skill: 'Reckoning',
    status: 'Normal',
    stats: { accuracy: 14, speed: 12, dodge: 18, electron: 16 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'bart',
    name: 'Bart',
    rarity: 'legendary',
    level: 1,
    exp: 0,
    expMax: 250,
    stars: 1,
    skill: 'Raid',
    status: 'Normal',
    stats: { accuracy: 5, speed: 3, dodge: 5, electron: 3 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'callisto',
    name: 'Callisto',
    rarity: 'legendary',
    level: 1,
    exp: 0,
    expMax: 250,
    stars: 1,
    skill: 'A Fire Rises',
    status: 'Normal',
    stats: { accuracy: 14, speed: 20, dodge: 15, electron: 20 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'carlos',
    name: 'Carlos',
    rarity: 'legendary',
    level: 1,
    exp: 0,
    expMax: 250,
    stars: 1,
    skill: 'Fear Fiend',
    status: 'Normal',
    stats: { accuracy: 15, speed: 5, dodge: 10, electron: 10 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'cassius',
    name: 'Cassius',
    rarity: 'legendary',
    level: 1,
    exp: 0,
    expMax: 250,
    stars: 1,
    skill: 'Knockout Blow',
    status: 'Normal',
    stats: { accuracy: 15, speed: 15, dodge: 15, electron: 15 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'circe',
    name: 'Circe',
    rarity: 'legendary',
    level: 1,
    exp: 0,
    expMax: 250,
    stars: 1,
    skill: 'Hex',
    status: 'Normal',
    stats: { accuracy: 15, speed: 10, dodge: 12, electron: 22 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'dilira',
    name: 'Dilira',
    rarity: 'legendary',
    level: 1,
    exp: 0,
    expMax: 250,
    stars: 1,
    skill: 'Renewal',
    status: 'Normal',
    stats: { accuracy: 10, speed: 15, dodge: 10, electron: 12 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'hellen',
    name: 'Hellen',
    rarity: 'legendary',
    level: 1,
    exp: 0,
    expMax: 250,
    stars: 1,
    skill: 'Rapid Reload',
    status: 'Normal',
    stats: { accuracy: 11, speed: 5, dodge: 7, electron: 16 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'krina-klaus',
    name: 'Krina Klaus',
    rarity: 'legendary',
    level: 1,
    exp: 0,
    expMax: 250,
    stars: 1,
    skill: "Winter's Gift",
    status: 'Normal',
    stats: { accuracy: 20, speed: 20, dodge: 20, electron: 20 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'maletiz',
    name: 'Maletiz',
    rarity: 'legendary',
    level: 1,
    exp: 0,
    expMax: 250,
    stars: 1,
    skill: 'Revenge',
    status: 'Normal',
    stats: { accuracy: 2, speed: 2, dodge: 2, electron: 2 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'marcus',
    name: 'Marcus',
    rarity: 'legendary',
    level: 1,
    exp: 0,
    expMax: 250,
    stars: 1,
    skill: 'Breakthrough',
    status: 'Normal',
    stats: { accuracy: 8, speed: 6, dodge: 8, electron: 3 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'medusa',
    name: 'Medusa',
    rarity: 'legendary',
    level: 1,
    exp: 0,
    expMax: 250,
    stars: 1,
    skill: 'Gorgon Gaze',
    status: 'Normal',
    stats: { accuracy: 20, speed: 14, dodge: 18, electron: 12 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'miller',
    name: 'Miller',
    rarity: 'legendary',
    level: 1,
    exp: 0,
    expMax: 250,
    stars: 1,
    skill: 'Pulverizer',
    status: 'Normal',
    stats: { accuracy: 0, speed: 0, dodge: 0, electron: 0 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'nora',
    name: 'Nora',
    rarity: 'legendary',
    level: 1,
    exp: 0,
    expMax: 250,
    stars: 1,
    skill: 'Massacre',
    status: 'Normal',
    stats: { accuracy: 9, speed: 4, dodge: 8, electron: 3 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'rafia',
    name: 'Rafia',
    rarity: 'legendary',
    level: 1,
    exp: 0,
    expMax: 250,
    stars: 1,
    skill: 'Stability Control',
    status: 'Normal',
    stats: { accuracy: 3, speed: 3, dodge: 5, electron: 2 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'rayo',
    name: 'Rayo',
    rarity: 'legendary',
    level: 1,
    exp: 0,
    expMax: 250,
    stars: 1,
    skill: 'Superior Command',
    status: 'Normal',
    stats: { accuracy: 13, speed: 13, dodge: 13, electron: 13 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'robert',
    name: 'Robert',
    rarity: 'legendary',
    level: 1,
    exp: 0,
    expMax: 250,
    stars: 1,
    skill: 'Massacre',
    status: 'Normal',
    stats: { accuracy: 20, speed: 4, dodge: 10, electron: 5 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'sandora',
    name: 'Sandora',
    rarity: 'legendary',
    level: 1,
    exp: 0,
    expMax: 250,
    stars: 1,
    skill: 'Lucky Strike',
    status: 'Normal',
    stats: { accuracy: 9, speed: 7, dodge: 8, electron: 7 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'singhri',
    name: 'Singhri',
    rarity: 'legendary',
    level: 1,
    exp: 0,
    expMax: 250,
    stars: 1,
    skill: 'Copycat',
    status: 'Normal',
    stats: { accuracy: 12, speed: 12, dodge: 12, electron: 12 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'stani',
    name: 'Stani',
    rarity: 'legendary',
    level: 1,
    exp: 0,
    expMax: 250,
    stars: 1,
    skill: 'Interference',
    status: 'Normal',
    stats: { accuracy: 5, speed: 8, dodge: 5, electron: 10 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'titan',
    name: 'Titan',
    rarity: 'legendary',
    level: 1,
    exp: 0,
    expMax: 250,
    stars: 1,
    skill: 'Adaptive Mutualism',
    status: 'Normal',
    stats: { accuracy: 35, speed: 35, dodge: 35, electron: 35 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'venus',
    name: 'Venus',
    rarity: 'legendary',
    level: 1,
    exp: 0,
    expMax: 250,
    stars: 1,
    skill: 'Gift of Romance',
    status: 'Normal',
    stats: { accuracy: 15, speed: 23, dodge: 24, electron: 12 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },

  // ----------------------------------------------------------
  // DIVINE — 35 commanders
  // ----------------------------------------------------------
  {
    id: 'carbuncle-cohort',
    name: 'Carbuncle Cohort',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Corrosive Coil',
    status: 'Normal',
    stats: { accuracy: 9, speed: 22, dodge: 11, electron: 15 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'deadly-duo',
    name: 'Deadly Duo',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Crucifer Sweep',
    status: 'Normal',
    stats: { accuracy: 19, speed: 17, dodge: 17, electron: 12 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'death-from-above',
    name: 'Death from Above',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: "Death's Clutches",
    status: 'Normal',
    stats: { accuracy: 24, speed: 24, dodge: 24, electron: 24 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'desolate-prayers',
    name: 'Desolate Prayers',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Decaying Wane',
    status: 'Normal',
    stats: { accuracy: 20, speed: 20, dodge: 13, electron: 18 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'dopplegangers',
    name: 'Dopplegangers',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Fierce Mutation',
    status: 'Normal',
    stats: { accuracy: 34, speed: 45, dodge: 44, electron: 45 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'enduring-chorus',
    name: 'Enduring Chorus',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Renewed Faith',
    status: 'Normal',
    stats: { accuracy: 8, speed: 19, dodge: 21, electron: 6 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'ererbus-errants',
    name: 'Ererbus Errants',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Shadow Storm',
    status: 'Normal',
    stats: { accuracy: 31, speed: 22, dodge: 11, electron: 34 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'eschaton-adventists',
    name: 'Eschaton Adventists',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Abject Humiliation',
    status: 'Normal',
    stats: { accuracy: 38, speed: 30, dodge: 31, electron: 25 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'eternal-terrors',
    name: 'Eternal Terrors',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Battle Preparations',
    status: 'Normal',
    stats: { accuracy: 29, speed: 10, dodge: 11, electron: 23 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'fairy-fiend',
    name: 'Fairy & Fiend',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Double Whammy',
    status: 'Normal',
    stats: { accuracy: 22, speed: 10, dodge: 20, electron: 10 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'fatal-furies',
    name: 'Fatal Furies',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Battering Barrage',
    status: 'Normal',
    stats: { accuracy: 30, speed: 15, dodge: 14, electron: 12 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'fearmongers',
    name: 'Fearmongers',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Omen of Doom',
    status: 'Normal',
    stats: { accuracy: 19, speed: 15, dodge: 12, electron: 21 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'feral-raptors',
    name: 'Feral Raptors',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Suicide Strike',
    status: 'Normal',
    stats: { accuracy: 18, speed: 14, dodge: 20, electron: 10 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'frontline-surge',
    name: 'Frontline Surge',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Pioneer Prowl',
    status: 'Normal',
    stats: { accuracy: 15, speed: 10, dodge: 17, electron: 3 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'hand-of-lelantos',
    name: 'Hand of Lelantos',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Unseen Strike',
    status: 'Normal',
    stats: { accuracy: 36, speed: 34, dodge: 32, electron: 34 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'hekatian-witnesses',
    name: 'Hekatian Witnesses',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Hekatian Edict',
    status: 'Normal',
    stats: { accuracy: 36, speed: 37, dodge: 35, electron: 34 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'homeric-hellions',
    name: 'Homeric Hellions',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'TBD',
    status: 'Normal',
    stats: { accuracy: 38, speed: 45, dodge: 25, electron: 12 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'impending-doom',
    name: 'Impending Doom',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Insidious Infliction',
    status: 'Normal',
    stats: { accuracy: 10, speed: 12, dodge: 7, electron: 17 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'indomitable-duo',
    name: 'Indomitable Duo',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Divine Barrier',
    status: 'Normal',
    stats: { accuracy: 12, speed: 25, dodge: 17, electron: 14 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'iron-maidens',
    name: 'Iron Maidens',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Fountain of Youth',
    status: 'Normal',
    stats: { accuracy: 10, speed: 21, dodge: 19, electron: 5 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'kismet-beams',
    name: 'Kismet Beams',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Supreme Smite',
    status: 'Normal',
    stats: { accuracy: 25, speed: 20, dodge: 10, electron: 5 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'leech-lurkers',
    name: 'Leech Lurkers',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Covert Syphon',
    status: 'Normal',
    stats: { accuracy: 17, speed: 12, dodge: 32, electron: 13 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'light-darkness',
    name: 'Light & Darkness',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Darkened Halo',
    status: 'Normal',
    stats: { accuracy: 12, speed: 15, dodge: 21, electron: 3 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'lurking-light',
    name: 'Lurking Light',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Phasing Halo',
    status: 'Normal',
    stats: { accuracy: 11, speed: 7, dodge: 24, electron: 12 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'pernicious-princes',
    name: 'Pernicious Princes',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Chain Vortex',
    status: 'Normal',
    stats: { accuracy: 20, speed: 20, dodge: 20, electron: 20 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'rays-of-destiny',
    name: 'Rays of Destiny',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Judgement',
    status: 'Normal',
    stats: { accuracy: 21, speed: 12, dodge: 15, electron: 9 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'rex-scuta',
    name: 'Rex Scuta',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Immunity',
    status: 'Normal',
    stats: { accuracy: 18, speed: 21, dodge: 15, electron: 18 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'the-ravagers',
    name: 'The Ravagers',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Smash and Grab',
    status: 'Normal',
    stats: { accuracy: 14, speed: 10, dodge: 13, electron: 11 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'suicidal-sirens',
    name: 'Suicidal Sirens',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Risky Surge',
    status: 'Normal',
    stats: { accuracy: 31, speed: 3, dodge: 12, electron: 20 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'summa-cum-laude',
    name: 'Summa Cum Laude',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Verdant Force',
    status: 'Normal',
    stats: { accuracy: 24, speed: 9, dodge: 23, electron: 12 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'tactical-wizards',
    name: 'Tactical Wizards',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Bamboozle',
    status: 'Normal',
    stats: { accuracy: 9, speed: 16, dodge: 12, electron: 22 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'the-twin-torpedoes',
    name: 'The Twin Torpedoes',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Sharpshooter Storm',
    status: 'Normal',
    stats: { accuracy: 30, speed: 0, dodge: 10, electron: 7 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'victory-roar',
    name: 'Victory Roar',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Eradicate',
    status: 'Normal',
    stats: { accuracy: 17, speed: 16, dodge: 19, electron: 15 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'wildfire',
    name: 'Wildfire',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Trigger Happy',
    status: 'Normal',
    stats: { accuracy: 35, speed: 5, dodge: 9, electron: 18 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
  {
    id: 'winter-knights',
    name: 'Winter Knights',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'TBD',
    status: 'Normal',
    stats: { accuracy: 15, speed: 34, dodge: 30, electron: 20 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
  },
];

// ============================================================
// DERIVED CONSTANTS
// ============================================================
export const TOTAL_COMMANDERS = COMMANDERS.length;

export const COMMANDERS_BY_RARITY: Record<Rarity, Commander[]> = {
  common: COMMANDERS.filter((c) => c.rarity === 'common'),
  super: COMMANDERS.filter((c) => c.rarity === 'super'),
  legendary: COMMANDERS.filter((c) => c.rarity === 'legendary'),
  divine: COMMANDERS.filter((c) => c.rarity === 'divine'),
};

export const COMMANDER_COUNT_BY_RARITY: Record<Rarity, number> = {
  common: COMMANDERS_BY_RARITY.common.length,
  super: COMMANDERS_BY_RARITY.super.length,
  legendary: COMMANDERS_BY_RARITY.legendary.length,
  divine: COMMANDERS_BY_RARITY.divine.length,
};

export const COMMANDER_IDS = COMMANDERS.map((c) => c.id);

export function getCommanderById(id: string): Commander | undefined {
  return COMMANDERS.find((c) => c.id === id);
}

export function getCommandersByRarity(rarity: Rarity): Commander[] {
  return COMMANDERS.filter((c) => c.rarity === rarity);
}

export function getCommandersBySkill(skillName: string): Commander[] {
  return COMMANDERS.filter(
    (c) => c.skill.toLowerCase() === skillName.toLowerCase()
  );
}
