import type { Gem } from './go2-gem-system';

export type Rarity = 'common' | 'super' | 'legendary' | 'divine';

export interface EquipmentItem {
  id: string;
  name: string;
  quality: 'S' | 'A' | 'B' | 'C' | 'D';
  icon: string;
}

export interface CommanderStats {
  accuracy: number;
  speed: number;
  dodge: number;
  electron: number;
}

export interface Commander {
  id: string;
  name: string;
  rarity: Rarity;
  level: number;
  exp: number;
  expMax: number;
  stars: number;
  skill: string;
  skillDescription: string;
  skillAffectedBy: string;
  status: string;
  stats: CommanderStats;
  growthRates: CommanderStats;
  equipment: {
    weapons: (EquipmentItem | null)[];
    defense: (EquipmentItem | null)[];
  };
  // ─── Gem System: 3 gem slots for stat boosts ───
  gems: (Gem | null)[];
  // ─── Hospital System: seconds remaining in hospital recovery ───
  injuryTime?: number;
  // ─── Fatality System: permanently dead commanders are removed ───
  isDead?: boolean;
}

// ============================================================
// RARITY VISUAL CONSTANTS
// ============================================================
export const RARITY_COLORS: Record<Rarity, string> = {
  common: '#4caf50',
  super: '#2196f3',
  legendary: '#9c27b0',
  divine: '#ff9800',
};

export const RARITY_DOT_CLASS: Record<Rarity, string> = {
  common: 'bg-[#4caf50]',
  super: 'bg-[#2196f3]',
  legendary: 'bg-[#9c27b0]',
  divine: 'bg-[#ff9800]',
};

export const QUALITY_COLORS: Record<string, { border: string; bg: string }> = {
  S: { border: 'border-[#ffd54f]', bg: 'bg-gradient-to-br from-[#b8860b] to-[#8b6914]' },
  A: { border: 'border-[#4caf50]', bg: 'bg-gradient-to-br from-[#2e7d32] to-[#1b5e20]' },
  B: { border: 'border-[#42a5f5]', bg: 'bg-gradient-to-br from-[#1565c0] to-[#0d47a1]' },
  C: { border: 'border-[#757575]', bg: 'bg-gradient-to-br from-[#616161] to-[#424242]' },
  D: { border: 'border-[#e53935]', bg: 'bg-gradient-to-br from-[#c62828] to-[#8e0000]' },
};

// ============================================================
// EXP MAX BY RARITY
// ============================================================
export const EXP_MAX_BY_RARITY: Record<Rarity, number> = {
  common: 180,
  super: 200,
  legendary: 250,
  divine: 300,
};

// ============================================================
// MERGE PROBABILITY CONSTANTS
// ============================================================
export const MERGE_PROBABILITIES = {
  sameRarity: {
    common: 0.80,    // Skill -> Skill: 80%
    super: 0.60,     // Super -> Super: 60%
    legendary: 0.40, // Legendary -> Legendary: 40%
    divine: 0.25,    // Divine -> Divine: 25%
  },
  crossRarity: 0.10, // Cross-rarity merge: 10%
} as const;

// ============================================================
// SKILL RARITY (Common) — Corsairs' Gold 150
// ============================================================
// Alicia, Angla, Donna, Essido, Heloyce, Jason, Jerome, Kelly,
// Lawrence, Mantie, Maxius, Motima, Natiya, Panis, Rayllf, Reggie,
// Shaba, Sofia, Taude, Tyren, Vinna, Wayne

// ============================================================
// SUPER RARITY — Corsairs' Gold 300
// ============================================================
// Andrew, Anna, Annata, Bruce, Eveline, Evi, Gastaf, Jakar,
// Joseph, Leo, Linda, Lynn, Nick, Penni, Raslin, Ringel,
// Rocky, Sylva, Sylla, Todd

// ============================================================
// LEGENDARY RARITY — Corsairs' Gold 600
// ============================================================
// Aileen, Bain, Bart, Callisto, Carlos, Cassius, Circe, Dilira,
// Hellen, Krina Klaus, Maletiz, Marcus, Medusa, Miller, Nora,
// Rafia, Rayo, Robert, Sandora, Singhri, Stani, Titan, Venus

// ============================================================
// DIVINE RARITY — Corsairs' Gold 600
// ============================================================
// Carbuncle Cohort, Deadly Duo, Death from Above, Desolate Prayers,
// Dopplegangers, Enduring Chorus, Ererbus Errants, Eschaton Adventists,
// Eternal Terrors, Fairy & Fiend, Fatal Furies, Fearmongers,
// Feral Raptors, Frontline Surge, Hand of Lelantos, Hekatian Witnesses,
// Homeric Hellions, Impending Doom, Indomitable Duo, Iron Maidens,
// Kismet Beams, Leech Lurkers, Light & Darkness, Lurking Light,
// Pernicious Princes, Rays of Destiny, Rex Scuta, The Ravagers,
// Suicidal Sirens, Summa Cum Laude, Tactical Wizards, The Twin Torpedoes,
// Victory Roar, Wildfire, Winter Knights

// ============================================================
// EMPTY EQUIPMENT TEMPLATE
// ============================================================
const EMPTY_EQUIPMENT = {
  weapons: [null, null, null, null] as (EquipmentItem | null)[],
  defense: [null, null, null, null] as (EquipmentItem | null)[],
};

// ============================================================
// EMPTY GEM SLOTS (3 slots — see go2-gem-system.ts)
// ============================================================
const EMPTY_GEMS = [null, null, null] as (Gem | null)[];

// ============================================================
// COMPLETE COMMANDER DATABASE (101 commanders)
// ============================================================
export const COMMANDERS: Commander[] = [
  // ----------------------------------------------------------
  // SKILL (Common) — 22 commanders
  // ----------------------------------------------------------
  {
    id: 'alicia',
    name: 'Alicia',
    rarity: 'common',
    level: 1,
    exp: 0,
    expMax: 180,
    stars: 1,
    skill: 'Inspiration',
    skillDescription: 'Has a chance to increase the damage dealt by the ship in the next slot of the formation by 30%.',
    skillAffectedBy: 'Accuracy',
    status: 'Normal',
    stats: { accuracy: 9, speed: 3, dodge: 7, electron: 5 },
    growthRates: { accuracy: 3.1, speed: 1.1, dodge: 2.2, electron: 1.1 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'angla',
    name: 'Angla',
    rarity: 'common',
    level: 1,
    exp: 0,
    expMax: 180,
    stars: 1,
    skill: 'Fleet EMT',
    skillDescription: 'Reduces hospital time and prevents anyone from killing the Commander.',
    skillAffectedBy: 'Dodge',
    status: 'Normal',
    stats: { accuracy: 4, speed: 4, dodge: 5, electron: 7 },
    growthRates: { accuracy: 0.9, speed: 1.2, dodge: 1.5, electron: 1.9 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'donna',
    name: 'Donna',
    rarity: 'common',
    level: 1,
    exp: 0,
    expMax: 180,
    stars: 1,
    skill: 'Defensive Intensity',
    skillDescription: 'Has a chance to restore 15% of maximum Shields at the start of each round.',
    skillAffectedBy: 'Speed',
    status: 'Normal',
    stats: { accuracy: 7, speed: 4, dodge: 4, electron: 8 },
    growthRates: { accuracy: 2.4, speed: 1.1, dodge: 0.9, electron: 2.3 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'essido',
    name: 'Essido',
    rarity: 'common',
    level: 1,
    exp: 0,
    expMax: 180,
    stars: 1,
    skill: 'Ship-based Expertise',
    skillDescription: 'Increases the damage of Ship-based Weapons.',
    skillAffectedBy: 'Accuracy',
    status: 'Normal',
    stats: { accuracy: 8, speed: 5, dodge: 6, electron: 8 },
    growthRates: { accuracy: 1.8, speed: 1.6, dodge: 2.0, electron: 1.9 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'heloyc',
    name: 'Heloyce',
    rarity: 'common',
    level: 1,
    exp: 0,
    expMax: 180,
    stars: 1,
    skill: 'Stability',
    skillDescription: 'Removes the formation penalty when a fleet is under attack and increases fleet stability.',
    skillAffectedBy: 'Dodge',
    status: 'Normal',
    stats: { accuracy: 7, speed: 2, dodge: 8, electron: 4 },
    growthRates: { accuracy: 1.6, speed: 0.5, dodge: 2.6, electron: 1.4 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'jason',
    name: 'Jason',
    rarity: 'common',
    level: 1,
    exp: 0,
    expMax: 180,
    stars: 1,
    skill: 'Save Energy',
    skillDescription: 'Has a chance to prevent modules from consuming He3 while attacking or defending.',
    skillAffectedBy: 'Electron',
    status: 'Normal',
    stats: { accuracy: 4, speed: 2, dodge: 5, electron: 5 },
    growthRates: { accuracy: 0.9, speed: 0.7, dodge: 1.6, electron: 1.5 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'jerome',
    name: 'Jerome',
    rarity: 'common',
    level: 1,
    exp: 0,
    expMax: 180,
    stars: 1,
    skill: 'Curse',
    skillDescription: 'If attacked, the enemy will receive 10% more damage the next round (stackable).',
    skillAffectedBy: 'Accuracy',
    status: 'Normal',
    stats: { accuracy: 5, speed: 8, dodge: 2, electron: 5 },
    growthRates: { accuracy: 1.2, speed: 2.5, dodge: 0.5, electron: 1.1 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'kelly',
    name: 'Kelly',
    rarity: 'common',
    level: 1,
    exp: 0,
    expMax: 180,
    stars: 1,
    skill: 'Resourceful',
    skillDescription: 'Restores 15% of maximum Structures per round.',
    skillAffectedBy: 'Speed',
    status: 'Normal',
    stats: { accuracy: 3, speed: 9, dodge: 6, electron: 5 },
    growthRates: { accuracy: 1.0, speed: 2.9, dodge: 1.8, electron: 1.8 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'lawrence',
    name: 'Lawrence',
    rarity: 'common',
    level: 1,
    exp: 0,
    expMax: 180,
    stars: 1,
    skill: 'Ballistic Expertise',
    skillDescription: 'Increases the damage of ballistic weapons.',
    skillAffectedBy: 'Accuracy',
    status: 'Normal',
    stats: { accuracy: 9, speed: 4, dodge: 6, electron: 8 },
    growthRates: { accuracy: 2.5, speed: 0.9, dodge: 1.4, electron: 2.0 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'mantie',
    name: 'Mantie',
    rarity: 'common',
    level: 1,
    exp: 0,
    expMax: 180,
    stars: 1,
    skill: 'Command Strike',
    skillDescription: "Increases the chances of killing the enemy commander at the cost of a 3% increase to the attacker's own fatality rate.",
    skillAffectedBy: 'Dodge',
    status: 'Normal',
    stats: { accuracy: 14, speed: 14, dodge: 14, electron: 14 },
    growthRates: { accuracy: 5.0, speed: 4.2, dodge: 4.8, electron: 3.2 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'maxius',
    name: 'Maxius',
    rarity: 'common',
    level: 1,
    exp: 0,
    expMax: 180,
    stars: 1,
    skill: 'Allied Strike',
    skillDescription: 'Has a chance to increase the accuracy of all friendly forces within 4 spaces by 5.',
    skillAffectedBy: 'Accuracy',
    status: 'Normal',
    stats: { accuracy: 10, speed: 0, dodge: 5, electron: 5 },
    growthRates: { accuracy: 2.9, speed: 0.0, dodge: 1.7, electron: 1.7 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'motima',
    name: 'Motima',
    rarity: 'common',
    level: 1,
    exp: 0,
    expMax: 180,
    stars: 1,
    skill: 'Accuracy',
    skillDescription: 'Has a chance to use the highest possible hit chance when attacking the enemy.',
    skillAffectedBy: 'Accuracy',
    status: 'Normal',
    stats: { accuracy: 8, speed: 2, dodge: 6, electron: 6 },
    growthRates: { accuracy: 2.6, speed: 0.6, dodge: 2.0, electron: 1.6 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'natiya',
    name: 'Natiya',
    rarity: 'common',
    level: 1,
    exp: 0,
    expMax: 180,
    stars: 1,
    skill: 'First Strike',
    skillDescription: "At the start of each round, has a chance to increase the Commander's speed by an amount equivalent to the Commander's level x 10.",
    skillAffectedBy: 'Speed',
    status: 'Normal',
    stats: { accuracy: 8, speed: 8, dodge: 6, electron: 8 },
    growthRates: { accuracy: 2.1, speed: 2.4, dodge: 1.8, electron: 2.0 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'panis',
    name: 'Panis',
    rarity: 'common',
    level: 1,
    exp: 0,
    expMax: 180,
    stars: 1,
    skill: 'Intercept',
    skillDescription: 'Increases the chance of air interception.',
    skillAffectedBy: 'Electron',
    status: 'Normal',
    stats: { accuracy: 5, speed: 5, dodge: 6, electron: 12 },
    growthRates: { accuracy: 1.8, speed: 1.7, dodge: 2.2, electron: 3.4 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'rayllf',
    name: 'Rayllf',
    rarity: 'common',
    level: 1,
    exp: 0,
    expMax: 180,
    stars: 1,
    skill: 'Armor Repair',
    skillDescription: 'Has a chance to increase ship defense by 5 per round. This effect lasts for 1 round.',
    skillAffectedBy: 'Speed',
    status: 'Normal',
    stats: { accuracy: 6, speed: 8, dodge: 7, electron: 7 },
    growthRates: { accuracy: 2.1, speed: 2.7, dodge: 2.6, electron: 2.4 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'reggie',
    name: 'Reggie',
    rarity: 'common',
    level: 1,
    exp: 0,
    expMax: 180,
    stars: 1,
    skill: 'Paralyze',
    skillDescription: "Has a chance to reduce the hostile Commander's attack power and block the use of his ability for the next round.",
    skillAffectedBy: 'Electron',
    status: 'Normal',
    stats: { accuracy: 5, speed: 3, dodge: 8, electron: 4 },
    growthRates: { accuracy: 1.8, speed: 1.0, dodge: 2.3, electron: 1.3 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'shaba',
    name: 'Shaba',
    rarity: 'common',
    level: 1,
    exp: 0,
    expMax: 180,
    stars: 1,
    skill: 'Allied Evasion',
    skillDescription: 'Increases the dodge chance of friendly forces within 4 spaces by 5 (stackable).',
    skillAffectedBy: 'Dodge',
    status: 'Normal',
    stats: { accuracy: 8, speed: 10, dodge: 5, electron: 5 },
    growthRates: { accuracy: 2.6, speed: 2.5, dodge: 1.4, electron: 1.4 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'sofia',
    name: 'Sofia',
    rarity: 'common',
    level: 1,
    exp: 0,
    expMax: 180,
    stars: 1,
    skill: 'Maneuvering',
    skillDescription: 'Has a chance to move an extra 3 spaces.',
    skillAffectedBy: 'Speed',
    status: 'Normal',
    stats: { accuracy: 7, speed: 5, dodge: 11, electron: 6 },
    growthRates: { accuracy: 1.5, speed: 1.3, dodge: 4.0, electron: 1.3 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'taude',
    name: 'Taude',
    rarity: 'common',
    level: 1,
    exp: 0,
    expMax: 180,
    stars: 1,
    skill: 'Lucky Shot',
    skillDescription: 'Has a chance to deal Lucky Shot, which increases the chance of shooting down a target by 50%.',
    skillAffectedBy: 'Accuracy',
    status: 'Normal',
    stats: { accuracy: 7, speed: 7, dodge: 4, electron: 4 },
    growthRates: { accuracy: 2.4, speed: 2.4, dodge: 1.5, electron: 1.0 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'tyren',
    name: 'Tyren',
    rarity: 'common',
    level: 1,
    exp: 0,
    expMax: 180,
    stars: 1,
    skill: 'Missile Expertise',
    skillDescription: 'Increases the damage of missiles.',
    skillAffectedBy: 'Accuracy',
    status: 'Normal',
    stats: { accuracy: 10, speed: 5, dodge: 7, electron: 5 },
    growthRates: { accuracy: 3.3, speed: 1.3, dodge: 2.2, electron: 1.6 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'vinna',
    name: 'Vinna',
    rarity: 'common',
    level: 1,
    exp: 0,
    expMax: 180,
    stars: 1,
    skill: 'Cunning',
    skillDescription: 'Reduces level-up requirements by 30%. Also has a chance to increase one stat by 10 when an attack connects. This effect lasts until the end of combat.',
    skillAffectedBy: 'Dodge',
    status: 'Normal',
    stats: { accuracy: 6, speed: 6, dodge: 6, electron: 6 },
    growthRates: { accuracy: 1.8, speed: 1.4, dodge: 1.6, electron: 1.5 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'wayne',
    name: 'Wayne',
    rarity: 'common',
    level: 1,
    exp: 0,
    expMax: 180,
    stars: 1,
    skill: 'Lucky Hit',
    skillDescription: 'Has a chance to deal double damage to the enemy.',
    skillAffectedBy: 'Accuracy',
    status: 'Normal',
    stats: { accuracy: 8, speed: 4, dodge: 9, electron: 2 },
    growthRates: { accuracy: 2.9, speed: 0.9, dodge: 2.1, electron: 0.7 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },

  // ----------------------------------------------------------
  // SUPER — 20 commanders
  // ----------------------------------------------------------
  {
    id: 'andrew',
    name: 'Andrew',
    rarity: 'super',
    level: 1,
    exp: 0,
    expMax: 200,
    stars: 1,
    skill: 'Acrobatics',
    skillDescription: "If Andrew's Dodge rating is higher than the enemy commander's Accuracy rating, Andrew's ships will not suffer any scattering damage.",
    skillAffectedBy: 'Dodge',
    status: 'Normal',
    stats: { accuracy: 5, speed: 10, dodge: 6, electron: 1 },
    growthRates: { accuracy: 2.2, speed: 5.0, dodge: 2.9, electron: 0.5 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'anna',
    name: 'Anna',
    rarity: 'super',
    level: 1,
    exp: 0,
    expMax: 200,
    stars: 1,
    skill: 'Pierce',
    skillDescription: 'Attacks have a chance to deal an extra 40% Piercing damage.',
    skillAffectedBy: 'Accuracy',
    status: 'Normal',
    stats: { accuracy: 9, speed: 8, dodge: 10, electron: 5 },
    growthRates: { accuracy: 4.3, speed: 4.2, dodge: 5.5, electron: 2.7 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'annata',
    name: 'Annata',
    rarity: 'super',
    level: 1,
    exp: 0,
    expMax: 200,
    stars: 1,
    skill: 'Allied Support',
    skillDescription: 'Increases the Shields and Structures of friendly forces within 4 steps by 8% after each round.',
    skillAffectedBy: 'Speed',
    status: 'Normal',
    stats: { accuracy: 10, speed: 8, dodge: 5, electron: 8 },
    growthRates: { accuracy: 4.3, speed: 3.9, dodge: 2.5, electron: 4.2 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'bruce',
    name: 'Bruce',
    rarity: 'super',
    level: 1,
    exp: 0,
    expMax: 200,
    stars: 1,
    skill: 'Drain Supplies',
    skillDescription: "Grants all offensive and defensive units a chance to increase the hostile fleet's He3 cost by 400%.",
    skillAffectedBy: 'Electron',
    status: 'Normal',
    stats: { accuracy: 6, speed: 8, dodge: 8, electron: 12 },
    growthRates: { accuracy: 3.4, speed: 4.3, dodge: 3.4, electron: 6.6 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'eveline',
    name: 'Eveline',
    rarity: 'super',
    level: 1,
    exp: 0,
    expMax: 200,
    stars: 1,
    skill: 'Find Weakness',
    skillDescription: "Has a chance to ignore the target's defenses.",
    skillAffectedBy: 'Accuracy',
    status: 'Normal',
    stats: { accuracy: 7, speed: 6, dodge: 9, electron: 5 },
    growthRates: { accuracy: 3.8, speed: 3.0, dodge: 4.0, electron: 2.2 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'evi',
    name: 'Evi',
    rarity: 'super',
    level: 1,
    exp: 0,
    expMax: 200,
    stars: 1,
    skill: 'Directional Expertise',
    skillDescription: 'Increases the damage of Directional Weapons.',
    skillAffectedBy: 'Accuracy',
    status: 'Normal',
    stats: { accuracy: 8, speed: 5, dodge: 9, electron: 5 },
    growthRates: { accuracy: 4.5, speed: 2.4, dodge: 4.0, electron: 2.3 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'gastaf',
    name: 'Gastaf',
    rarity: 'super',
    level: 1,
    exp: 0,
    expMax: 200,
    stars: 1,
    skill: 'Deadly Strike',
    skillDescription: 'Has an increased chance to deal critical strikes.',
    skillAffectedBy: 'Accuracy',
    status: 'Normal',
    stats: { accuracy: 12, speed: 0, dodge: 10, electron: 7 },
    growthRates: { accuracy: 6.3, speed: 0.0, dodge: 5.7, electron: 3.8 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'jakar',
    name: 'Jakar',
    rarity: 'super',
    level: 1,
    exp: 0,
    expMax: 200,
    stars: 1,
    skill: 'Aegis Shatter',
    skillDescription: "If his Accuracy rating is higher than an enemy commander's Dodge rating, the enemy fleet's Defense and Agility stats will be ignored during each attack.",
    skillAffectedBy: 'Accuracy',
    status: 'Normal',
    stats: { accuracy: 9, speed: 3, dodge: 5, electron: 4 },
    growthRates: { accuracy: 4.5, speed: 1.6, dodge: 2.5, electron: 2.0 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'joseph',
    name: 'Joseph',
    rarity: 'super',
    level: 1,
    exp: 0,
    expMax: 200,
    stars: 1,
    skill: 'Vengeance',
    skillDescription: "If the value of Joseph's Electron attribute exceeds that of his opposing commander, he will reflect 20% of damage taken back to its source.",
    skillAffectedBy: 'Electron',
    status: 'Normal',
    stats: { accuracy: 4, speed: 10, dodge: 7, electron: 17 },
    growthRates: { accuracy: 2.2, speed: 4.4, dodge: 3.3, electron: 7.4 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'leo',
    name: 'Leo',
    rarity: 'super',
    level: 1,
    exp: 0,
    expMax: 200,
    stars: 1,
    skill: 'Intimidate',
    skillDescription: 'Has a chance to reduce the Durability, Structures and Shields of enemies within 2 steps by 5% after every turn.',
    skillAffectedBy: 'Electron',
    status: 'Normal',
    stats: { accuracy: 5, speed: 9, dodge: 6, electron: 8 },
    growthRates: { accuracy: 2.8, speed: 3.9, dodge: 3.5, electron: 4.4 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'linda',
    name: 'Linda',
    rarity: 'super',
    level: 1,
    exp: 0,
    expMax: 200,
    stars: 1,
    skill: 'Broadside',
    skillDescription: 'Attacks have a chance to deal an extra 50% Scattering damage.',
    skillAffectedBy: 'Accuracy',
    status: 'Normal',
    stats: { accuracy: 10, speed: 9, dodge: 7, electron: 7 },
    growthRates: { accuracy: 4.6, speed: 4.0, dodge: 3.8, electron: 3.2 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'lynn',
    name: 'Lynn',
    rarity: 'super',
    level: 1,
    exp: 0,
    expMax: 200,
    stars: 1,
    skill: 'Victory Rush',
    skillDescription: "Lynn's ships deal 10% more damage each round for every space her fleet moves.",
    skillAffectedBy: 'Spaces Moved',
    status: 'Normal',
    stats: { accuracy: 8, speed: 5, dodge: 6, electron: 3 },
    growthRates: { accuracy: 4.6, speed: 2.5, dodge: 3.4, electron: 1.5 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'nick',
    name: 'Nick',
    rarity: 'super',
    level: 1,
    exp: 0,
    expMax: 200,
    stars: 1,
    skill: 'Divine Intervention',
    skillDescription: 'Has a chance to avoid damage.',
    skillAffectedBy: 'Dodge',
    status: 'Normal',
    stats: { accuracy: 5, speed: 4, dodge: 5, electron: 2 },
    growthRates: { accuracy: 2.1, speed: 2.0, dodge: 2.3, electron: 0.9 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'penni',
    name: 'Penni',
    rarity: 'super',
    level: 1,
    exp: 0,
    expMax: 200,
    stars: 1,
    skill: 'Last Stand',
    skillDescription: 'Has a chance to deal triple damage when attacking, but also inflicts 10% damage to the ship.',
    skillAffectedBy: 'Accuracy',
    status: 'Normal',
    stats: { accuracy: 10, speed: 10, dodge: 10, electron: 10 },
    growthRates: { accuracy: 5.0, speed: 4.9, dodge: 5.3, electron: 4.5 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'raslin',
    name: 'Raslin',
    rarity: 'super',
    level: 1,
    exp: 0,
    expMax: 200,
    stars: 1,
    skill: 'Fear',
    skillDescription: "Grants a chance to reduce an enemy's attack power by 50% the next round.",
    skillAffectedBy: 'Electron',
    status: 'Normal',
    stats: { accuracy: 8, speed: 7, dodge: 9, electron: 10 },
    growthRates: { accuracy: 4.6, speed: 3.6, dodge: 4.8, electron: 4.9 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'ringel',
    name: 'Ringel',
    rarity: 'super',
    level: 1,
    exp: 0,
    expMax: 200,
    stars: 1,
    skill: 'Ignite',
    skillDescription: 'Has a chance to inflict an additional 30% of the damage last dealt to the enemy when the next round begins.',
    skillAffectedBy: 'Accuracy',
    status: 'Normal',
    stats: { accuracy: 9, speed: 5, dodge: 9, electron: 3 },
    growthRates: { accuracy: 4.4, speed: 2.6, dodge: 3.9, electron: 1.6 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'rocky',
    name: 'Rocky',
    rarity: 'super',
    level: 1,
    exp: 0,
    expMax: 200,
    stars: 1,
    skill: 'Brutal Strength',
    skillDescription: "Each time Rocky's ships destroy all ships in a single fleet slot, his ships will double their attack power. (Can be stacked up to 8 times.)",
    skillAffectedBy: 'Independent',
    status: 'Normal',
    stats: { accuracy: 12, speed: 4, dodge: 8, electron: 5 },
    growthRates: { accuracy: 5.5, speed: 2.3, dodge: 3.9, electron: 2.8 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'sylva',
    name: 'Sylva',
    rarity: 'super',
    level: 1,
    exp: 0,
    expMax: 200,
    stars: 1,
    skill: 'Smash',
    skillDescription: 'Has a chance to deal up to 2.5 times the damage to a fortress.',
    skillAffectedBy: 'Independent',
    status: 'Normal',
    stats: { accuracy: 7, speed: 5, dodge: 5, electron: 2 },
    growthRates: { accuracy: 3.3, speed: 2.8, dodge: 2.6, electron: 0.9 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'sylla',
    name: 'Sylla',
    rarity: 'super',
    level: 1,
    exp: 0,
    expMax: 200,
    stars: 1,
    skill: 'Fleet Link',
    skillDescription: 'Has a chance to reduce damage taken by 15% and enables all ships to share damage.',
    skillAffectedBy: 'Dodge',
    status: 'Normal',
    stats: { accuracy: 5, speed: 9, dodge: 5, electron: 5 },
    growthRates: { accuracy: 2.1, speed: 4.6, dodge: 2.5, electron: 2.7 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'todd',
    name: 'Todd',
    rarity: 'super',
    level: 1,
    exp: 0,
    expMax: 200,
    stars: 1,
    skill: 'Consecutive Strike',
    skillDescription: 'While attacking, there is a chance of attacking the target twice.',
    skillAffectedBy: 'Accuracy',
    status: 'Normal',
    stats: { accuracy: 30, speed: 8, dodge: 5, electron: 6 },
    growthRates: { accuracy: 15.1, speed: 4.2, dodge: 2.3, electron: 2.8 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },

  // ----------------------------------------------------------
  // LEGENDARY — 24 commanders
  // ----------------------------------------------------------
  {
    id: 'aileen',
    name: 'Aileen',
    rarity: 'legendary',
    level: 1,
    exp: 0,
    expMax: 250,
    stars: 1,
    skill: 'Command Break',
    skillDescription: "Has a chance to reduce the hostile Commander's stats to 0.",
    skillAffectedBy: 'Electron & Speed',
    status: 'Normal',
    stats: { accuracy: 8, speed: 8, dodge: 8, electron: 8 },
    growthRates: { accuracy: 5.6, speed: 5.4, dodge: 5.3, electron: 5.6 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'bain',
    name: 'Bain',
    rarity: 'legendary',
    level: 1,
    exp: 0,
    expMax: 250,
    stars: 1,
    skill: 'Reckoning',
    skillDescription: "When Bain is attacked, there is a chance to reduce the enemy commander's 4 attributes to 0 for the next Round.",
    skillAffectedBy: 'Accuracy and Dodge',
    status: 'Normal',
    stats: { accuracy: 14, speed: 12, dodge: 18, electron: 16 },
    growthRates: { accuracy: 9.1, speed: 9.1, dodge: 13.1, electron: 11.4 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'bart',
    name: 'Bart',
    rarity: 'legendary',
    level: 1,
    exp: 0,
    expMax: 250,
    stars: 1,
    skill: 'Raid',
    skillDescription: 'Has a chance to dodge attacks and increase Attack Power by 15% for one round.',
    skillAffectedBy: 'Electron & Speed',
    status: 'Normal',
    stats: { accuracy: 5, speed: 3, dodge: 5, electron: 3 },
    growthRates: { accuracy: 3.6, speed: 2.0, dodge: 3.7, electron: 2.1 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'callisto',
    name: 'Callisto',
    rarity: 'legendary',
    level: 1,
    exp: 0,
    expMax: 250,
    stars: 1,
    skill: 'A Fire Rises',
    skillDescription: 'While attacking, has a chance to increase attack strength by 10%. Can be stacked and remains in effect until end of the battle.',
    skillAffectedBy: 'Accuracy',
    status: 'Normal',
    stats: { accuracy: 14, speed: 20, dodge: 15, electron: 20 },
    growthRates: { accuracy: 9.3, speed: 13.2, dodge: 9.8, electron: 15.4 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'carlos',
    name: 'Carlos',
    rarity: 'legendary',
    level: 1,
    exp: 0,
    expMax: 250,
    stars: 1,
    skill: 'Fear Fiend',
    skillDescription: 'Deals additional damage to enemy fleet ship structures. Actual amounts are based on the amount of damage dealt to enemy ship shields.',
    skillAffectedBy: 'Accuracy and Speed',
    status: 'Normal',
    stats: { accuracy: 15, speed: 5, dodge: 10, electron: 10 },
    growthRates: { accuracy: 10.1, speed: 3.4, dodge: 7.0, electron: 6.5 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'cassius',
    name: 'Cassius',
    rarity: 'legendary',
    level: 1,
    exp: 0,
    expMax: 250,
    stars: 1,
    skill: 'Knockout Blow',
    skillDescription: 'When attacking, Cassius has a chance to move the enemy fleet back 3 spaces. Can only be used once per turn.',
    skillAffectedBy: 'Accuracy and Dodge',
    status: 'Normal',
    stats: { accuracy: 15, speed: 15, dodge: 15, electron: 15 },
    growthRates: { accuracy: 9.4, speed: 11.0, dodge: 11.0, electron: 9.6 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'circe',
    name: 'Circe',
    rarity: 'legendary',
    level: 1,
    exp: 0,
    expMax: 250,
    stars: 1,
    skill: 'Hex',
    skillDescription: 'While defending against an attack, has a chance to prevent the enemy commander from using skills in the next Round.',
    skillAffectedBy: 'Accuracy and Dodge',
    status: 'Normal',
    stats: { accuracy: 15, speed: 10, dodge: 12, electron: 22 },
    growthRates: { accuracy: 9.7, speed: 7.6, dodge: 9.2, electron: 16.1 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'dilira',
    name: 'Dilira',
    rarity: 'legendary',
    level: 1,
    exp: 0,
    expMax: 250,
    stars: 1,
    skill: 'Renewal',
    skillDescription: 'Has a chance to fully restore Shields and Durability.',
    skillAffectedBy: 'Speed',
    status: 'Normal',
    stats: { accuracy: 10, speed: 15, dodge: 10, electron: 12 },
    growthRates: { accuracy: 7.3, speed: 11.4, dodge: 6.6, electron: 8.0 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'hellen',
    name: 'Hellen',
    rarity: 'legendary',
    level: 1,
    exp: 0,
    expMax: 250,
    stars: 1,
    skill: 'Rapid Reload',
    skillDescription: 'When attacking, there is a chance to instantly finish reloading weapons.',
    skillAffectedBy: 'Accuracy & Electron',
    status: 'Normal',
    stats: { accuracy: 11, speed: 5, dodge: 7, electron: 16 },
    growthRates: { accuracy: 8.0, speed: 3.2, dodge: 4.6, electron: 10.5 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'krina-klaus',
    name: 'Krina Klaus',
    rarity: 'legendary',
    level: 1,
    exp: 0,
    expMax: 250,
    stars: 1,
    skill: "Winter's Gift",
    skillDescription: "Chance to increase overall ship defense of allied fleets within 4 spaces by 10 at the end of Krina Klaus' turn.",
    skillAffectedBy: 'Dodge',
    status: 'Normal',
    stats: { accuracy: 20, speed: 20, dodge: 20, electron: 20 },
    growthRates: { accuracy: 15.3, speed: 14.0, dodge: 13.4, electron: 13.7 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'maletiz',
    name: 'Maletiz',
    rarity: 'legendary',
    level: 1,
    exp: 0,
    expMax: 250,
    stars: 1,
    skill: 'Revenge',
    skillDescription: 'Has a chance to absorb all damage and reflect it back to the attacker.',
    skillAffectedBy: 'Dodge & Electron',
    status: 'Normal',
    stats: { accuracy: 2, speed: 2, dodge: 2, electron: 2 },
    growthRates: { accuracy: 1.5, speed: 1.4, dodge: 1.4, electron: 1.4 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'marcus',
    name: 'Marcus',
    rarity: 'legendary',
    level: 1,
    exp: 0,
    expMax: 250,
    stars: 1,
    skill: 'Breakthrough',
    skillDescription: "Has a chance to be unaffected by the target's Shield, Shield Modules and Stability during attack.",
    skillAffectedBy: 'Accuracy & Speed',
    status: 'Normal',
    stats: { accuracy: 8, speed: 6, dodge: 8, electron: 3 },
    growthRates: { accuracy: 5.4, speed: 4.6, dodge: 6.0, electron: 2.0 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'medusa',
    name: 'Medusa',
    rarity: 'legendary',
    level: 1,
    exp: 0,
    expMax: 250,
    stars: 1,
    skill: 'Gorgon Gaze',
    skillDescription: 'Has a chance to cause the enemy fleet to skip its next Round when Medusa is attacked.',
    skillAffectedBy: 'Dodge & Electron',
    status: 'Normal',
    stats: { accuracy: 20, speed: 14, dodge: 18, electron: 12 },
    growthRates: { accuracy: 14.3, speed: 10.9, dodge: 12.3, electron: 8.4 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'miller',
    name: 'Miller',
    rarity: 'legendary',
    level: 1,
    exp: 0,
    expMax: 250,
    stars: 1,
    skill: 'Pulverizer',
    skillDescription: "Miller's fleet deal an extra 300% damage to all Light Armored targets.",
    skillAffectedBy: 'Independent',
    status: 'Normal',
    stats: { accuracy: 0, speed: 0, dodge: 0, electron: 0 },
    growthRates: { accuracy: 0.0, speed: 0.0, dodge: 0.0, electron: 0.0 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'nora',
    name: 'Nora',
    rarity: 'legendary',
    level: 1,
    exp: 0,
    expMax: 250,
    stars: 1,
    skill: 'Massacre',
    skillDescription: 'Has a chance to destroy enemy troops when they attack. This effect can only be initiated once per round.',
    skillAffectedBy: 'Accuracy & Dodge',
    status: 'Normal',
    stats: { accuracy: 9, speed: 4, dodge: 8, electron: 3 },
    growthRates: { accuracy: 6.7, speed: 2.6, dodge: 5.1, electron: 2.1 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'rafia',
    name: 'Rafia',
    rarity: 'legendary',
    level: 1,
    exp: 0,
    expMax: 250,
    stars: 1,
    skill: 'Stability Control',
    skillDescription: "If the total combined value of Rafia's 4 base stats exceeds those of the opposing commander, the stability of her ships will be increased to their maximum strength.",
    skillAffectedBy: 'Total Stats',
    status: 'Normal',
    stats: { accuracy: 3, speed: 3, dodge: 5, electron: 2 },
    growthRates: { accuracy: 1.9, speed: 2.1, dodge: 3.7, electron: 1.4 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'rayo',
    name: 'Rayo',
    rarity: 'legendary',
    level: 1,
    exp: 0,
    expMax: 250,
    stars: 1,
    skill: 'Superior Command',
    skillDescription: "Nullifies the effect of an enemy commander's ability if the sum of his Base Stats is higher than that of the enemy commander.",
    skillAffectedBy: 'Total Stats',
    status: 'Normal',
    stats: { accuracy: 13, speed: 13, dodge: 13, electron: 13 },
    growthRates: { accuracy: 8.3, speed: 9.4, dodge: 9.3, electron: 9.1 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'robert',
    name: 'Robert',
    rarity: 'legendary',
    level: 1,
    exp: 0,
    expMax: 250,
    stars: 1,
    skill: 'Massacre',
    skillDescription: "If the total value of his 4 base stats exceeds that of the enemy commander's, double attacks will trigger a critical strike for all ships in the following fleet slot.",
    skillAffectedBy: 'Total Stats',
    status: 'Normal',
    stats: { accuracy: 20, speed: 4, dodge: 10, electron: 5 },
    growthRates: { accuracy: 14.3, speed: 3.0, dodge: 7.6, electron: 3.1 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'sandora',
    name: 'Sandora',
    rarity: 'legendary',
    level: 1,
    exp: 0,
    expMax: 250,
    stars: 1,
    skill: 'Lucky Strike',
    skillDescription: 'Has a chance to deal 30% Scattering damage to all enemy forces.',
    skillAffectedBy: 'Accuracy & Speed',
    status: 'Normal',
    stats: { accuracy: 9, speed: 7, dodge: 8, electron: 7 },
    growthRates: { accuracy: 6.5, speed: 4.9, dodge: 5.2, electron: 5.0 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'singhri',
    name: 'Singhri',
    rarity: 'legendary',
    level: 1,
    exp: 0,
    expMax: 250,
    stars: 1,
    skill: 'Copycat',
    skillDescription: "Copies an enemy Commander's skills when attacking or defending. (skill effects copied will not be retained after combat has concluded.)",
    skillAffectedBy: 'Independent',
    status: 'Normal',
    stats: { accuracy: 12, speed: 12, dodge: 12, electron: 12 },
    growthRates: { accuracy: 8.3, speed: 7.7, dodge: 9.2, electron: 8.2 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'stani',
    name: 'Stani',
    rarity: 'legendary',
    level: 1,
    exp: 0,
    expMax: 250,
    stars: 1,
    skill: 'Interference',
    skillDescription: 'Has a chance to prevent the enemy from moving and attacking for the next round.',
    skillAffectedBy: 'Accuracy & Electron',
    status: 'Normal',
    stats: { accuracy: 5, speed: 8, dodge: 5, electron: 10 },
    growthRates: { accuracy: 3.3, speed: 6.0, dodge: 3.6, electron: 7.2 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'titan',
    name: 'Titan',
    rarity: 'legendary',
    level: 1,
    exp: 0,
    expMax: 250,
    stars: 1,
    skill: 'Adaptive Mutualism',
    skillDescription: "Each time Titan levels up, each of Titan's base attributes increases by 5 points on top of the attribute's growth rate.",
    skillAffectedBy: 'None',
    status: 'Normal',
    stats: { accuracy: 35, speed: 35, dodge: 35, electron: 35 },
    growthRates: { accuracy: 22.2, speed: 23.3, dodge: 24.2, electron: 23.8 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'venus',
    name: 'Venus',
    rarity: 'legendary',
    level: 1,
    exp: 0,
    expMax: 250,
    stars: 1,
    skill: 'Gift of Romance',
    skillDescription: 'Increases damage negation of all shield modules in the fleet.',
    skillAffectedBy: 'Dodge & Speed',
    status: 'Normal',
    stats: { accuracy: 15, speed: 23, dodge: 24, electron: 12 },
    growthRates: { accuracy: 9.7, speed: 15.0, dodge: 18.4, electron: 7.5 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },

  // ----------------------------------------------------------
  // DIVINE — 35 commanders
  // ----------------------------------------------------------
  {
    id: 'carbuncle-cohort',
    name: 'Carbuncle Cohort',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Corrosive Coil',
    skillDescription: 'Will reflect 20% of the original damage taken, and then further reduce damage taken by 15%, and finally spread the remaining damage equally across all ships in the fleet.',
    skillAffectedBy: 'Dodge',
    status: 'Normal',
    stats: { accuracy: 9, speed: 22, dodge: 11, electron: 15 },
    growthRates: { accuracy: 8.8, speed: 21.1, dodge: 12.1, electron: 14.1 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'deadly-duo',
    name: 'Deadly Duo',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Crucifer Sweep',
    skillDescription: 'This skill has a chance to deal an additional 50% Scattering Damage and 40% Piercing damage during all attacks.',
    skillAffectedBy: 'Accuracy',
    status: 'Normal',
    stats: { accuracy: 19, speed: 17, dodge: 17, electron: 12 },
    growthRates: { accuracy: 17.7, speed: 16.6, dodge: 17.6, electron: 11.3 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'death-from-above',
    name: 'Death from Above',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: "Death's Clutches",
    skillDescription: "If Death from Above successfully deals either a double or critical attack while the sum of their 4 base stats exceed that of the enemy's, all adjacent ships will deal double attacks or critical strikes. Enemy abilities will be nullified as well.",
    skillAffectedBy: 'All',
    status: 'Normal',
    stats: { accuracy: 24, speed: 24, dodge: 24, electron: 24 },
    growthRates: { accuracy: 20.4, speed: 27.2, dodge: 22.0, electron: 25.4 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'desolate-prayers',
    name: 'Desolate Prayers',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Decaying Wane',
    skillDescription: 'This skill has the chance to lower all 4 stats of an enemy commander to 0. The target will also be immobilized in the next round.',
    skillAffectedBy: 'Speed and Accuracy',
    status: 'Normal',
    stats: { accuracy: 20, speed: 20, dodge: 13, electron: 18 },
    growthRates: { accuracy: 22.5, speed: 22.4, dodge: 13.9, electron: 15.3 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'dopplegangers',
    name: 'Dopplegangers',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Fierce Mutation',
    skillDescription: "Each time Dopplegangers level up, the total increment of the 4 attributes is increased by an additional 5 points. At the beginning of each engagement, copies the enemy commander's skill until the end of the engagement.",
    skillAffectedBy: 'All',
    status: 'Normal',
    stats: { accuracy: 34, speed: 45, dodge: 44, electron: 45 },
    growthRates: { accuracy: 32.6, speed: 40.3, dodge: 43.1, electron: 44.1 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'enduring-chorus',
    name: 'Enduring Chorus',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Renewed Faith',
    skillDescription: 'Has a chance each round to fully restore all Shield and Structure points and increase the Dodge attribute of all friendly forces within 4 spaces by 5. This buff can be stacked.',
    skillAffectedBy: 'Speed',
    status: 'Normal',
    stats: { accuracy: 8, speed: 19, dodge: 21, electron: 6 },
    growthRates: { accuracy: 7.3, speed: 21.8, dodge: 18.3, electron: 5.5 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'ererbus-errants',
    name: 'Ererbus Errants',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Shadow Storm',
    skillDescription: 'Each time Erebus Errants levels up, the total value of their 4 attributes will increase by an additional 5 points. Also has a chance to negate all damage when attacked.',
    skillAffectedBy: 'Dodge',
    status: 'Normal',
    stats: { accuracy: 31, speed: 22, dodge: 11, electron: 34 },
    growthRates: { accuracy: 35.1, speed: 19.3, dodge: 11.3, electron: 37.7 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'eschaton-adventists',
    name: 'Eschaton Adventists',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Abject Humiliation',
    skillDescription: "Each time levels up, the total increment of four attributes is increased by an additional 5 points. When attacking, there is a chance to reduce the enemy Commander's stats to 0 for the next round.",
    skillAffectedBy: 'Accuracy and Dodge',
    status: 'Normal',
    stats: { accuracy: 38, speed: 30, dodge: 31, electron: 25 },
    growthRates: { accuracy: 41.4, speed: 30.2, dodge: 27.0, electron: 24.9 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'eternal-terrors',
    name: 'Eternal Terrors',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Battle Preparations',
    skillDescription: "While attacking, chance to instantly reload all weapons, and reduce an enemy commander's attack power and block their abilities next round.",
    skillAffectedBy: 'Accuracy and Electron',
    status: 'Normal',
    stats: { accuracy: 29, speed: 10, dodge: 11, electron: 23 },
    growthRates: { accuracy: 31.3, speed: 8.6, dodge: 12.3, electron: 20.5 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'fairy-fiend',
    name: 'Fairy & Fiend',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Double Whammy',
    skillDescription: "Chance to deal additional structural damage, ignoring the enemy's defenses altogether. Actual damage is based on amount dealt to enemy shields.",
    skillAffectedBy: 'Accuracy and Speed',
    status: 'Normal',
    stats: { accuracy: 22, speed: 10, dodge: 20, electron: 10 },
    growthRates: { accuracy: 21.9, speed: 10.7, dodge: 21.9, electron: 11.3 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'fatal-furies',
    name: 'Fatal Furies',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Battering Barrage',
    skillDescription: "This skill has chance to deal 2x damage to the enemy. Total damage is unaffected by target's Shield, Modules, and Stability.",
    skillAffectedBy: 'Accuracy and Speed',
    status: 'Normal',
    stats: { accuracy: 30, speed: 15, dodge: 14, electron: 12 },
    growthRates: { accuracy: 28.3, speed: 14.3, dodge: 16.0, electron: 13.4 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'fearmongers',
    name: 'Fearmongers',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Omen of Doom',
    skillDescription: 'While attacking or defending, has a chance to increase enemy He3 cost by 5 times and reduce enemy attack power by 50% until end of next round.',
    skillAffectedBy: 'Electron',
    status: 'Normal',
    stats: { accuracy: 19, speed: 15, dodge: 12, electron: 21 },
    growthRates: { accuracy: 17.8, speed: 17.1, dodge: 10.7, electron: 21.6 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'feral-raptors',
    name: 'Feral Raptors',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Suicide Strike',
    skillDescription: 'Chance to deal 6x damage while attacking but also reflects 10% of damage back to your ships.',
    skillAffectedBy: 'Accuracy and Speed',
    status: 'Normal',
    stats: { accuracy: 18, speed: 14, dodge: 20, electron: 10 },
    growthRates: { accuracy: 18.0, speed: 15.5, dodge: 22.7, electron: 9.7 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'frontline-surge',
    name: 'Frontline Surge',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Pioneer Prowl',
    skillDescription: 'This skill has a chance to move fleets an additional 3 spaces and increase attack values by 10% for every space that fleet moves.',
    skillAffectedBy: 'Speed',
    status: 'Normal',
    stats: { accuracy: 15, speed: 10, dodge: 17, electron: 3 },
    growthRates: { accuracy: 13.6, speed: 9.8, dodge: 17.5, electron: 2.9 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'hand-of-lelantos',
    name: 'Hand of Lelantos',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Unseen Strike',
    skillDescription: "Each time level up, the total increment of four attributes is increased by an additional 5 points. If Accuracy is higher than the enemy commander's Dodge, all attacks will ignore the enemy fleet's Overall Ship Defense and Agility.",
    skillAffectedBy: 'Accuracy',
    status: 'Normal',
    stats: { accuracy: 36, speed: 34, dodge: 32, electron: 34 },
    growthRates: { accuracy: 39.3, speed: 30.5, dodge: 30.6, electron: 36.1 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'hekatian-witnesses',
    name: 'Hekatian Witnesses',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Hekatian Edict',
    skillDescription: 'Each time level up, the total increment of four attributes is increased by an additional 5 points. Have a chance to destroy an entire ship stack each time it is dealt damage.',
    skillAffectedBy: 'Accuracy and Dodge',
    status: 'Normal',
    stats: { accuracy: 36, speed: 37, dodge: 35, electron: 34 },
    growthRates: { accuracy: 31.7, speed: 34.3, dodge: 39.5, electron: 30.1 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'homeric-hellions',
    name: 'Homeric Hellions',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'TBD',
    skillDescription: 'Each time level up, the total increment of four attributes is increased by an additional 5 points.',
    skillAffectedBy: 'All',
    status: 'Normal',
    stats: { accuracy: 38, speed: 45, dodge: 25, electron: 12 },
    growthRates: { accuracy: 37.8, speed: 45.9, dodge: 25.9, electron: 10.7 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'impending-doom',
    name: 'Impending Doom',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Insidious Infliction',
    skillDescription: 'This skill increases the dodge rate of your ships and, if attacked, will deal 10% more damage the next round (stackable).',
    skillAffectedBy: 'Dodge & Electron',
    status: 'Normal',
    stats: { accuracy: 10, speed: 12, dodge: 7, electron: 17 },
    growthRates: { accuracy: 11.0, speed: 13.0, dodge: 7.9, electron: 15.3 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'indomitable-duo',
    name: 'Indomitable Duo',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Divine Barrier',
    skillDescription: "If Dodge rating is higher than the enemy commander's Accuracy rating, scattering damage and formation penalty is ignored while under attack. Also increases fleet stability.",
    skillAffectedBy: 'Dodge',
    status: 'Normal',
    stats: { accuracy: 12, speed: 25, dodge: 17, electron: 14 },
    growthRates: { accuracy: 13.4, speed: 22.5, dodge: 17.4, electron: 15.0 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'iron-maidens',
    name: 'Iron Maidens',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Fountain of Youth',
    skillDescription: "If the total combined value of base stats exceed those of the enemy commander, ships' stability will increase to their maximum and has the chance to fully restore Shields and Structures each round.",
    skillAffectedBy: 'Speed and Dodge',
    status: 'Normal',
    stats: { accuracy: 10, speed: 21, dodge: 19, electron: 5 },
    growthRates: { accuracy: 9.4, speed: 22.7, dodge: 21.0, electron: 5.7 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'kismet-beams',
    name: 'Kismet Beams',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Supreme Smite',
    skillDescription: 'This skill has a chance to deal 2x damage to the enemy and 30% Scattering damage to all enemy fleets.',
    skillAffectedBy: 'Accuracy and Speed',
    status: 'Normal',
    stats: { accuracy: 25, speed: 20, dodge: 10, electron: 5 },
    growthRates: { accuracy: 27.9, speed: 21.0, dodge: 10.3, electron: 4.3 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'leech-lurkers',
    name: 'Leech Lurkers',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Covert Syphon',
    skillDescription: 'Reduces the chance of being hit and increases Attack Power by 15% for one round. Additional chance to reduce the Durability, Structures and Shields of enemies within 2 steps by 5% each turn.',
    skillAffectedBy: 'Accuracy and Speed',
    status: 'Normal',
    stats: { accuracy: 17, speed: 12, dodge: 32, electron: 13 },
    growthRates: { accuracy: 18.3, speed: 13.7, dodge: 35.0, electron: 12.4 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'light-darkness',
    name: 'Light & Darkness',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Darkened Halo',
    skillDescription: 'This skill increases the Shield and Structure values of friendly fleets within 4 steps by 8% after each round and has a chance to reduce enemy Durability, structures, and Shields within 2 steps by 5% after every turn.',
    skillAffectedBy: 'Speed',
    status: 'Normal',
    stats: { accuracy: 12, speed: 15, dodge: 21, electron: 3 },
    growthRates: { accuracy: 10.5, speed: 14.7, dodge: 22.1, electron: 2.7 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'lurking-light',
    name: 'Lurking Light',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Phasing Halo',
    skillDescription: 'Has a chance to dodge attacks, increase Attack Power by 15% for one round, and increase Shield and Structure values of friendly forces within 4 spaces by 8% at end of the round.',
    skillAffectedBy: 'Dodge & Speed',
    status: 'Normal',
    stats: { accuracy: 11, speed: 7, dodge: 24, electron: 12 },
    growthRates: { accuracy: 11.5, speed: 7.0, dodge: 24.3, electron: 11.9 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'pernicious-princes',
    name: 'Pernicious Princes',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Chain Vortex',
    skillDescription: "If the sum of 4 base stats exceed that of the enemy commander's, any double attack or critical strike will ignore enemy fleet Defense and Agility and also trigger a double attack or critical strike for the ships in the following fleet slot.",
    skillAffectedBy: 'All',
    status: 'Normal',
    stats: { accuracy: 20, speed: 20, dodge: 20, electron: 20 },
    growthRates: { accuracy: 19.7, speed: 21.3, dodge: 22.0, electron: 22.2 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'rays-of-destiny',
    name: 'Rays of Destiny',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Judgement',
    skillDescription: 'This skill has a chance to deal an additional 30% Scattering damage to all enemy forces and reflect all absorbed damage to its source.',
    skillAffectedBy: 'Total Stats',
    status: 'Normal',
    stats: { accuracy: 21, speed: 12, dodge: 15, electron: 9 },
    growthRates: { accuracy: 21.9, speed: 11.1, dodge: 14.9, electron: 8.8 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'rex-scuta',
    name: 'Rex Scuta',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Immunity',
    skillDescription: "If the sum of Base Stats exceed those of the enemy commander, the Stability of ships will increase to the maximum. Effect also nullifies the enemy commander's abilities.",
    skillAffectedBy: 'All',
    status: 'Normal',
    stats: { accuracy: 18, speed: 21, dodge: 15, electron: 18 },
    growthRates: { accuracy: 18.9, speed: 18.0, dodge: 15.7, electron: 17.0 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'the-ravagers',
    name: 'The Ravagers',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Smash and Grab',
    skillDescription: 'If all ships in a single enemy fleet slot are destroyed by ships in a single fleet slot, Attack Power of those ships will double. This buff can be stacked up to 8 times. There is also a chance that those ships will instantly reload all weapons.',
    skillAffectedBy: 'Accuracy and Electron',
    status: 'Normal',
    stats: { accuracy: 14, speed: 10, dodge: 13, electron: 11 },
    growthRates: { accuracy: 13.6, speed: 8.9, dodge: 14.9, electron: 9.8 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'suicidal-sirens',
    name: 'Suicidal Sirens',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Risky Surge',
    skillDescription: 'Chance to deal 3x damage and instantly reload weapons, but also reflects 10% damage to attacking ship.',
    skillAffectedBy: 'Accuracy & Electron',
    status: 'Normal',
    stats: { accuracy: 31, speed: 3, dodge: 12, electron: 20 },
    growthRates: { accuracy: 34.8, speed: 2.6, dodge: 12.2, electron: 19.4 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'summa-cum-laude',
    name: 'Summa Cum Laude',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Verdant Force',
    skillDescription: "Has a chance to be unaffected by the target's Shield, Shield Modules and Stability during an attack and instantly reload all weapons after the attack.",
    skillAffectedBy: 'Accuracy & Speed',
    status: 'Normal',
    stats: { accuracy: 24, speed: 9, dodge: 23, electron: 12 },
    growthRates: { accuracy: 24.6, speed: 7.8, dodge: 19.8, electron: 10.5 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'tactical-wizards',
    name: 'Tactical Wizards',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Bamboozle',
    skillDescription: 'Chance to avoid damage and increase enemy He3 costs by up to 5 times.',
    skillAffectedBy: 'Dodge & Electron',
    status: 'Normal',
    stats: { accuracy: 9, speed: 16, dodge: 12, electron: 22 },
    growthRates: { accuracy: 9.3, speed: 16.7, dodge: 10.9, electron: 25.2 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'the-twin-torpedoes',
    name: 'The Twin Torpedoes',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Sharpshooter Storm',
    skillDescription: 'This skill increases the critical strike rate of the commanded fleet and the chance of attacking the target twice.',
    skillAffectedBy: 'Accuracy',
    status: 'Normal',
    stats: { accuracy: 30, speed: 0, dodge: 10, electron: 7 },
    growthRates: { accuracy: 25.5, speed: 0.0, dodge: 10.5, electron: 8.0 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'victory-roar',
    name: 'Victory Roar',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Eradicate',
    skillDescription: "This skill has the potential to cancel out a target's defenses and deal triple damage when attacking, but also inflicts 10% recoil damage to the ship commanded.",
    skillAffectedBy: 'Accuracy',
    status: 'Normal',
    stats: { accuracy: 17, speed: 16, dodge: 19, electron: 15 },
    growthRates: { accuracy: 18.7, speed: 17.4, dodge: 19.2, electron: 15.7 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'wildfire',
    name: 'Wildfire',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'Trigger Happy',
    skillDescription: 'Chance to deal 30% Scattering damage to enemy ships and instantly reload weapons.',
    skillAffectedBy: 'Accuracy and Electron',
    status: 'Normal',
    stats: { accuracy: 35, speed: 5, dodge: 9, electron: 18 },
    growthRates: { accuracy: 30.7, speed: 5.2, dodge: 9.3, electron: 16.4 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
  {
    id: 'winter-knights',
    name: 'Winter Knights',
    rarity: 'divine',
    level: 1,
    exp: 0,
    expMax: 300,
    stars: 1,
    skill: 'TBD',
    skillDescription: 'Each time level up, the total increment of four attributes is increased by an additional 5 points.',
    skillAffectedBy: 'All',
    status: 'Normal',
    stats: { accuracy: 15, speed: 34, dodge: 30, electron: 20 },
    growthRates: { accuracy: 16.7, speed: 38.4, dodge: 30.1, electron: 19.3 },
    equipment: { weapons: [null, null, null, null], defense: [null, null, null, null] },
    gems: EMPTY_GEMS,
  },
];

// ============================================================
// DERIVED CONSTANTS
// ============================================================
export const TOTAL_COMMANDERS = COMMANDERS.length;

export const COMMANDERS_BY_RARITY: Record<Rarity, Commander[]> = {
  common: COMMANDERS.filter((c) => c.rarity === 'common'),
  super: COMMANDERS.filter((c) => c.rarity === 'super'),
  legendary: COMMANDERS.filter((c) => c.rarity === 'legendary'),
  divine: COMMANDERS.filter((c) => c.rarity === 'divine'),
};

export const COMMANDER_COUNT_BY_RARITY: Record<Rarity, number> = {
  common: COMMANDERS_BY_RARITY.common.length,
  super: COMMANDERS_BY_RARITY.super.length,
  legendary: COMMANDERS_BY_RARITY.legendary.length,
  divine: COMMANDERS_BY_RARITY.divine.length,
};

export const COMMANDER_IDS = COMMANDERS.map((c) => c.id);

export function getCommanderById(id: string): Commander | undefined {
  return COMMANDERS.find((c) => c.id === id);
}

export function getCommandersByRarity(rarity: Rarity): Commander[] {
  return COMMANDERS.filter((c) => c.rarity === rarity);
}

export function getCommandersBySkill(skillName: string): Commander[] {
  return COMMANDERS.filter(
    (c) => c.skill.toLowerCase() === skillName.toLowerCase()
  );
}


// ============================================================
// EQUIPMENT QUALITY BONUSES (percentage added to stats)
// ============================================================
export const WEAPON_QUALITY_BONUS: Record<string, { accuracy: number; electron: number }> = {
  S: { accuracy: 15, electron: 10 },
  A: { accuracy: 10, electron: 7 },
  B: { accuracy: 7, electron: 5 },
  C: { accuracy: 5, electron: 3 },
  D: { accuracy: 3, electron: 1 },
};

export const DEFENSE_QUALITY_BONUS: Record<string, { dodge: number; speed: number }> = {
  S: { dodge: 15, speed: 10 },
  A: { dodge: 10, speed: 7 },
  B: { dodge: 7, speed: 5 },
  C: { dodge: 5, speed: 3 },
  D: { dodge: 3, speed: 1 },
};

// ============================================================
// STAT CALCULATION FUNCTIONS
// ============================================================

/**
 * Calculate a commander's stats at a given level.
 * Formula: stat_at_level = base_stat + (growth_rate × (level - 1))
 */
export function calculateStatsAtLevel(cmd: Commander, level: number): CommanderStats {
  const lvl = Math.max(1, Math.min(50, level));
  return {
    accuracy: Math.round(cmd.stats.accuracy + cmd.growthRates.accuracy * (lvl - 1)),
    speed: Math.round(cmd.stats.speed + cmd.growthRates.speed * (lvl - 1)),
    dodge: Math.round(cmd.stats.dodge + cmd.growthRates.dodge * (lvl - 1)),
    electron: Math.round(cmd.stats.electron + cmd.growthRates.electron * (lvl - 1)),
  };
}

/**
 * Get the EXP required for a specific level based on rarity.
 * Formula: expForLevel = base × (1.15 ^ level)
 */
export function getExpForLevel(rarity: Rarity, level: number): number {
  const base: Record<Rarity, number> = {
    common: 180,
    super: 200,
    legendary: 250,
    divine: 300,
  };
  const lvl = Math.max(1, Math.min(50, level));
  return Math.floor(base[rarity] * Math.pow(1.15, lvl));
}

/**
 * Get the cumulative EXP required to reach a specific level from level 1.
 */
export function getCumulativeExpToLevel(rarity: Rarity, level: number): number {
  let total = 0;
  for (let i = 1; i < level; i++) {
    total += getExpForLevel(rarity, i);
  }
  return total;
}

/**
 * Calculate equipment bonuses for a commander.
 * Returns the total percentage bonuses from all equipped items.
 */
export function calculateEquipmentBonuses(cmd: Commander): {
  accuracyBonus: number;
  speedBonus: number;
  dodgeBonus: number;
  electronBonus: number;
} {
  let accuracyBonus = 0;
  let electronBonus = 0;
  let dodgeBonus = 0;
  let speedBonus = 0;

  // Sum weapon bonuses
  for (const weapon of cmd.equipment.weapons) {
    if (weapon) {
      const bonus = WEAPON_QUALITY_BONUS[weapon.quality];
      if (bonus) {
        accuracyBonus += bonus.accuracy;
        electronBonus += bonus.electron;
      }
    }
  }

  // Sum defense bonuses
  for (const defense of cmd.equipment.defense) {
    if (defense) {
      const bonus = DEFENSE_QUALITY_BONUS[defense.quality];
      if (bonus) {
        dodgeBonus += bonus.dodge;
        speedBonus += bonus.speed;
      }
    }
  }

  return { accuracyBonus, speedBonus, dodgeBonus, electronBonus };
}

/**
 * Calculate a commander's final stats at a given level with equipment bonuses applied.
 * Equipment bonuses are applied as percentage increases to the level-adjusted stats.
 */
export function calculateFinalStats(cmd: Commander, level: number): CommanderStats {
  const baseStats = calculateStatsAtLevel(cmd, level);
  const equipment = calculateEquipmentBonuses(cmd);

  return {
    accuracy: Math.round(baseStats.accuracy * (1 + equipment.accuracyBonus / 100)),
    speed: Math.round(baseStats.speed * (1 + equipment.speedBonus / 100)),
    dodge: Math.round(baseStats.dodge * (1 + equipment.dodgeBonus / 100)),
    electron: Math.round(baseStats.electron * (1 + equipment.electronBonus / 100)),
  };
}

/**
 * Get the stat increases that will happen on the next level up.
 */
export function getNextLevelBonus(cmd: Commander): CommanderStats {
  return {
    accuracy: Math.round(cmd.growthRates.accuracy),
    speed: Math.round(cmd.growthRates.speed),
    dodge: Math.round(cmd.growthRates.dodge),
    electron: Math.round(cmd.growthRates.electron),
  };
}
